### ISSUE TITLE
release plans?

### ISSUE THREAD

**Issue by FreederFree** [PAYONE-GmbH/magento-2#1]
Are there any release plans for this? I would like to get a shop running until mid november including a payone integration. Since magento 2 has been release for almost one year now, i wondered why such an important payment extension is still missing?

**Comment by FreederFree** [comment]
Just saw that it is on. Why is it only available if i'm logged in?

**Comment by fjbender** [comment]
We just pushed it to GitHub today, since we still had some refactoring to do. Hope you can use this release for your project :)

**Comment by FreederFree** [comment]
Oh nice, thank you! So I think I've got the right timing ;)
