### ISSUE TITLE
Offline capture for preauthorization disables creditmemo.

### ISSUE THREAD

**Issue by fischamhaken** [PAYONE-GmbH/magento-2#100]
I found this piece of Code in Observer:

$oInvoice->setRequestedCaptureCase(Invoice::CAPTURE_OFFLINE);
-> this is fix in Observer\Transactionstatus\Paid.php!!

But if invoice is captured offline for advance_payment - I could not do creditmemo because invoiced status will not arrive in pmi. Set this to CAPTURE_ONLINE sends information to pmi an I can do a creditmemo, but I get message 907 - An error occured while processing this transaction (wrong parameters) when I try do make a creditmemo with less than the complete invoice items (i.e. creditmemo for 2 of three parts)

**Comment by fjbender** [comment]
You should always use capture online, otherwise our platform will not get notified about the capture.

When you receive error 907 this is only temporal. It just means that the asynchronous response about the capture has not yet been processed. Just wait a couple of minutes and try again (see Transaction Status log for details).

I just tried to reproduce this and a partial refund works fine.

If you encounter any issues about this, feel free to reopen this issue.

Cheers
Florian

**Comment by fischamhaken** [comment]
Hi Florian,

but have a look into the Code:

\Observer\Transactionstatus\Paid.php

$oInvoice->setRequestedCaptureCase(Invoice::CAPTURE_OFFLINE);

is fix!

Is it the right way for me to replace this with Code like this:

		if ($oOrder->getPayoneAuthmode() === 'preauthorization') {
			$oInvoice->setRequestedCaptureCase(Invoice::CAPTURE_ONLINE);
		} else {
			$oInvoice->setRequestedCaptureCase(Invoice::CAPTURE_OFFLINE);
		}

?? 
Thanks for your reply,
Stefan

**Comment by fjbender** [comment]
Yes, you're right. I'll take a closer look into this.

**Comment by domeglic** [comment]
Any update on this? A workaround is simple but I would rather have it done in the extension already so there are no modifications.

**Comment by fjbender** [comment]
Hasn't this been fixed with #105 ?

**Comment by fischamhaken** [comment]
I can confirm it is fixed with with #105 by deleting automatically invoice capture for advanced payment from module. Even if I don't understand why it's not possible to do an online capture for advanced payment. At the moment I have placed workaround like this:

        // order is not guaranteed to exist if using transaction status forwarding
        if (null === $oOrder){
            return;
        }

        $oInvoice = $this->invoiceService->prepareInvoice($oOrder);

		if ($oOrder->getPayoneAuthmode() === 'preauthorization') {
			$oInvoice->setRequestedCaptureCase(Invoice::CAPTURE_ONLINE);
		} else {
			$oInvoice->setRequestedCaptureCase(Invoice::CAPTURE_OFFLINE);
		}

Don't know if this is a good idea, but I don't won't to online capture many of advanced payments orders every day manually.

Cheers,
Stefan
