### ISSUE TITLE
Magento Enterprise database split compatibility (Update)

### ISSUE THREAD

**Issue by kostyagh** [PAYONE-GmbH/magento-2#104]
Hello @fjbender 
I have checked both closed issues.
https://github.com/PAYONE-GmbH/magento-2/issues/22
https://github.com/PAYONE-GmbH/magento-2/issues/75

You do not need to do any significant changes to make your extension supports Magento EE.
These are basic rules for supporting EE.
http://devdocs.magento.com/guides/v2.1/config-guide/multi-master/multi-master.html#config-ee-multidb-opts

You need to overwrite code where you use SQL to Magento model(PDO) style:
The bad code style examples preventing to use DB spliting:

https://github.com/PAYONE-GmbH/magento-2/blob/master/Helper/Database.php#L132
https://github.com/PAYONE-GmbH/magento-2/blob/master/Helper/Database.php#L219

**Comment by fjbender** [comment]
Thanks for the feedback!

We're currently trying to obtain an EE license for testing purposes from Magento and then we'll address this issue.

**Comment by fjbender** [comment]
@kostyagh we now have PR #131 which should fix this issue. We still don't have an EE license from Magento. Can you confirm this enables the database split in EE?

**Comment by davidverholen** [comment]
there is one addition. in The UpgradeSchema, the getConnection for quote tables needs the connection name for the checkout database or the upgrade will fail with sharded databases.

Meaning you just have to call it like:
$setup->getConnection('checkout')

**Comment by fjbender** [comment]
Thanks :) That's the problem when you can't test it in an actual EE shop.

**Comment by davidverholen** [comment]
yes, it must be really awful currently for 3-rd party extension vendors. Be sure we will test some things over the next months ;)
