### ISSUE TITLE
Magento 2.2 compatibility

### ISSUE THREAD

**Issue by alexkuk** [PAYONE-GmbH/magento-2#107]
The current version is not Magento 2.2 compatible.

**Comment by FATCHIP-GmbH** [comment]
We are now working on that topic.
Internal Ticket: https://integrator.payone.de/jira/browse/MAG2-42

**Comment by xBitsSec** [comment]
Can you update composer php requires to PHP 7.1. Thx :)

**Comment by fjbender** [comment]
@xBitsSec see #123
