### ISSUE TITLE
Missing messages when returning from bad credit card payment

### ISSUE THREAD

**Issue by fischamhaken** [PAYONE-GmbH/magento-2#108]
In the credit card payment I noticed the following: In the IFrame heavy credit card errors are displayed before sending. However, e.g. enter an incorrect valid-to date or refuse payment for other reasons after exiting the I-frame, then the return goes to /checkout/

However, Magento's new one-page checkout consists of two parts, 1. the shipping address, 2. the payment method. The payment method is reached in Magento's Checkout via the "Next" button to the URL /checkout/#payment. This would be the correct jumpback URL.

Even worse is that no error message or error is issued after jumpback. There is a return to the /checkout without any indication that an error has occurred in the credit card payment.

This also happens when you pay with 3-D Secure, if you put the "Cancel" button on secure page, but also with other errors, which occur only on the secure side.

In my opinion, this is a bug of the extension, there should be at least one hint "An error occurred while the payment was made" or "Bad payment data were specified" with a return to the /checkout/#payment (with an open I frame) and usually red-marked fields.

Maybe I am wrong and have only configured incorrect, but I have searched everything. Or is there another way to achieve a correct error recovery? Otherwise this should be implemented urgently.

Magento 2.1.7 with Payone Extension 1.3.5

Greetings,
Stefan

**Comment by fischamhaken** [comment]
Are there any updates or comments on the subject?

**Comment by fjbender** [comment]
When I enter a wrong expiry date, I get the following error:
![Mage Checkout with wrong expiry date](https://talisker.fbender.de/fbender/dump/magento2_expiry.png)

However, it is true that the jumpback URL for the "Cancel" action on the third party page (e.g. 3D Secure) goes back to /checkout instead of /checkout/#payment. This should be fixed.

**Comment by fischamhaken** [comment]
You can not test it in test mode! You must take a valid-to date that is invalid and lies in the future! The only way to see the error behaviour in the test mode is to make a 3-D secure order, and abort on the 3D secure page.

If you use an incorrect check-digit or an incorrect valid-to date, which is in the future, during the live- checkout, it is simply returned to the checkout page, without error indication. And foolishly even on the /checkout start, better would be to /checkout/#payment

btw: why are the error messages are not translated?

**Comment by fjbender** [comment]
Okay, thanks for the clarification. This issue will be addressed to make sure the customer gets back to /checkout/#payment in any case.

I suppose the Denglish error messages are due to my weird shop configuration. Or is there a general problem? If yes, we should discuss this in a separate issue.

**Comment by fischamhaken** [comment]
Yes, to first answer, no, to your suppose :-) I have clean Magento Setup with complete german translation, but errors in validation fields occur in english. I´ve seen something of a magento bug in validation.js in versions < 2.2 (missing __ trans function) - but I dont know how Payone Extension handles the validation of the input fields. 

https://magento.stackexchange.com/questions/162195/translate-checkout-strings
https://github.com/magento/magento2/issues/4883

**Comment by fjbender** [comment]
Okay, I think we should address this separately. Can you open another issue for this, please?

Cheers
Florian

**Comment by fischamhaken** [comment]
Hi,

are there any Updates relating the problem with the wrong checkout url in error case?
(to make sure the customer gets back to /checkout/#payment in any case)

Cheers,
Stefan

**Comment by fjbender** [comment]
We're still working on this - it's a minor change, but still somebody has to find the time to do it :/

**Comment by fjbender** [comment]
Fixed with #117
