### ISSUE TITLE
Credit Card Error messages are not translated

### ISSUE THREAD

**Issue by fischamhaken** [PAYONE-GmbH/magento-2#110]
M2.1.7

Error messages for wrong card information are not translated - even if german translation exists.

**Comment by fjbender** [comment]
I can't reproduce this. Once the language is set, messages are displayed in the corresponding language:
![image](https://user-images.githubusercontent.com/7370694/31598350-65def956-b24d-11e7-9299-8a5b348ea09c.png)
(In admin backend PAYONE -> General -> Payment Creditcard -> Custom Styling hosted iFrame)

![image](https://user-images.githubusercontent.com/7370694/31598326-450daa7e-b24d-11e7-8d3c-d8275616d5c8.png)

However, I agree that this is quite hard to find.

**Comment by fischamhaken** [comment]
Hi,
yes, its really hard to find :-) 
I actualized this.... 
![clipboard03](https://user-images.githubusercontent.com/30490386/31618518-75c9cd4c-b292-11e7-8606-2f33fb96bf96.jpg)

..but error is displayed in english:

![clipboard02](https://user-images.githubusercontent.com/30490386/31618568-991fadfc-b292-11e7-94de-a4f14e265986.jpg)

I found code for translation via grep for this not translated string (next screenshot) in 
/vendor/payone-gmbh/magento-2/view/frontend/web/js/view/payment/method-renderer/creditcard-method.js: $t("Please enter complete data.")

![clipboard01](https://user-images.githubusercontent.com/30490386/31618601-ac9f4a40-b292-11e7-9658-48145ef883e4.jpg)

I added translation for this to /i18n/de_DE.csv and after clearing cache - voilá: error message is translated. So it seems, some messages are translated, and some not. It's strange to see your translation for "Expiry date invalid..." - I could not find this string in whole magento installation?! Is this translated remote?

**Comment by fjbender** [comment]
Yes, some of the messages are generated on our platform (i.e. whenever card date had been verified) and some are generated from the shop (i.e. when fields are incomplete).

Can you provide a PR for the added translations? :)

**Comment by fischamhaken** [comment]
Just for information - if others have same issue:
These are the strings i can not translate:
![clipboard05](https://user-images.githubusercontent.com/30490386/31705297-21febee4-b3e5-11e7-8c88-60f1bd2f8605.jpg)
![clipboard06](https://user-images.githubusercontent.com/30490386/31705298-221e05d8-b3e5-11e7-8732-75b3b6db3135.jpg)
![clipboard07](https://user-images.githubusercontent.com/30490386/31705299-223c24e6-b3e5-11e7-8bec-5d861a1df751.jpg)

The only translation working is 
"Please enter complete data.","Bitte geben Sie die Kreditkartendaten vollstaendig ein."

Sorry, I don't know how to create PR (Pull Request??)
Instead I added you my de_DE.csv

[de_DE.zip](https://github.com/PAYONE-GmbH/magento-2/files/1393726/de_DE.zip)

**Comment by fjbender** [comment]
Thanks for the updated CSV, I will create a pull request with that.

The other messages should be translateable through the (hidden) language selection in the admin backend, as they are generated platform-side.

**Comment by fischamhaken** [comment]
Another point at this issue: Is it possible that call to credit card provider does not accept language ("deutsch") - in test cases I noticed that 3D-Secure Page is complete english too, have a look at screenshot.
![clipboard09](https://user-images.githubusercontent.com/30490386/31759510-ef9798fe-b4b1-11e7-8f6d-010c672a47ac.jpg)

**Comment by fjbender** [comment]
As I see it, our 3D Secure test page is only available in English. In live mode, the 3D Secure page is provided by the bank of the customer, which should automatically be in the right language.
