### ISSUE TITLE
Refund orders with several variants for one configurable

### ISSUE THREAD

**Issue by david-fuehr** [PAYONE-GmbH/magento-2#121]
When an order with a payone payment method was placed and captured, the refund during creditmemo creation fails in specific cases.

Given: 
```
$order->getAllItems() = [
  0 => ['productId' => 1, 'sku' = 'abc_1', 'type' => 'configurable'],
  1 => ['productId' => 1, 'sku' = 'abc_1', 'type' => 'simple'],
  2 => ['productId' => 1, 'sku' = 'abc_2', 'type' => 'configurable'],
  3 => ['productId' => 1, 'sku' = 'abc_2', 'type' => 'simple'],
  4 => ['productId' => 2, 'sku' = 'def_1', 'type' => 'configurable'],
  5 => ['productId' => 2, 'sku' = 'def_1', 'type' => 'simple'],
];

$aPositions = $creditmemo->getItems() = [
  0 => ['orderItemId' => 11, 'productId' => 1,  'sku' = 'abc_1'],
];
```

Then the following code is executed for every order item (no dummy positions) and will create an invalid API call (`\Payone\Core\Model\Api\Invoice::addProductItem`):
```
[...]
if ($aPositions !== false && array_key_exists($oItem->getProductId(), $aPositions) !== false) {
  $dItemAmount = $aPositions[$oItem->getProductId()];
}
[...]
```
Order item `0` is included in parameters, because `productId` of creditmemo item matches order items product id. That is *correct*, because `sku` matches also.
Order item `2` is included in parameters, because `productId` of creditmemo item matches order items product id. That is *not correct*, because `sku` does not match.

**Comment by fjbender** [comment]
For order items `0` and `1` in your `getAllItems()` list, the `sku` and `productId` are the same, thus I'd say that both items must be included. Or is that a typo? Or maybe I'm not quite understanding.

**Comment by fjbender** [comment]
Okay, I see :) Basically, this can be avoided by adding the `sku` as an additional condition for adding the product in the `\Payone\Core\Model\Api\Invoice::addProductItem` method, right? I'm not quite sure about possible side effects, but we'll check and come back to you.

**Comment by david-fuehr** [comment]
Thank you, that should do. Meanwhile I figured out, that in our case the configuration `payone_general/invoicing/transmit_enabled = 0` is a suitable workaround for that issue.

**Comment by fjbender** [comment]
This workaround should work for most payment methods, but be advised that some methods require the transmission of a basket (e.g. factoring providers "safe invoice") and this transmit_enabled flag will be overridden for those.

**Comment by fjbender** [comment]
#127 is supposed to fix this issue. I can't really test this with our test data - can you confirm this fixes your issue?

**Comment by david-fuehr** [comment]
The code looks good to me. Currently I am not able to set up a test scenario either. I'll give an update, as soon as I can test it.

**Comment by sydekumf** [comment]
Works fine for debits now, invoices/capture not explicitly tested as we have a different workflow for that. But debits (Gutschriften) work perfect, thanks.

**Comment by fjbender** [comment]
Thanks for the feedback!
