### ISSUE TITLE
Creating a new non-payone creditmemo shows exception

### ISSUE THREAD

**Issue by domeglic** [PAYONE-GmbH/magento-2#128]
When I try to create a creditmemo for an order not paid by a Payone payment I get an **Invalid Method** exception.
`1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Magento\OfflinePayments\Model\Banktransfer\Interceptor::needsSepaDataOnDebit`

Magento version: 2.2
Module version: commit beb41039651f978c396980ec8198b78c8cb39af8
Only stops working in Developer mode, in Production it just logs the error but the error is still there.

see:
- [Block that triggers the exception](https://github.com/PAYONE-GmbH/magento-2/blob/master/Block/Adminhtml/Order/Creditmemo/SepaData.php#L82)
- [Layout that adds the block](https://github.com/PAYONE-GmbH/magento-2/blob/master/view/adminhtml/layout/sales_order_creditmemo_new.xml)
- [Template of the block](https://github.com/PAYONE-GmbH/magento-2/blob/master/view/adminhtml/templates/sepadata.phtml)

**Comment by fjbender** [comment]
I could reproduce this, thanks for your feedback. We'll fix this.

**Comment by fjbender** [comment]
Fixed with #129.
