### ISSUE TITLE
Module cannot be compiled without dev dependencies

### ISSUE THREAD

**Issue by davidverholen** [PAYONE-GmbH/magento-2#133]
As a best practice, we do not deploy the dev dependencies (including phpunit) to the production systems (composer install --no-dev).

Unfortunately, there is an error during compilation of the module when phpunit is not installed

Errors during compilation:                                   
  	Payone\Core\Model\Test\PayoneObjectManager                  
  		Class PHPUnit\Framework\TestCase does not exist

**Comment by fjbender** [comment]
Thanks for your feedback. We'll take a look and fix this.

**Comment by fjbender** [comment]
Fixed with #136
