### ISSUE TITLE
Error 1610 when Invoicing with cart price rule

### ISSUE THREAD

**Issue by petertroeger** [PAYONE-GmbH/magento-2#135]
Hi :)
I encounter the following error in Magento 2.1.10 with v. 1.3.6 and also with Magento 2.2.1 and v. 2.0.2,
fresh installation (and also our running shop).

How to reproduce the Problem:

1. Fresh installation of Magento
2. Only install the Payone Plugin
3. Setup Invoice in Payone
4. Authorize Method - > preauthorization, Transmit invoice information -> Yes
5. Create a Cart Price Rule with 30% discount, no conitions, no coupon
6. Create a configurable product with color and size
7. Buy said product with invoice
8. Try to invoice (capture) the sale in magento backend

Error-Message: Article list faulty or incomplete, (Falsche Parameter). ErrorCode: 1610

The problem seems to somehow be with discounted carts and possibly in combination with invoicing.

**Comment by fjbender** [comment]
Hi @petertroeger,

I suspect this is a rounding problem. Can you please contact our technical support team at tech.support@bspayone.com with details to the transaction (MID, TXID, timestamp) and refer to this Github issue?

Thanks!

**Comment by domeglic** [comment]
I have the same problem and it is not a rounding error. The request is missing the discount position entirely.
If the discount is a coupon then it worked, but if the discount is an automatic cart rule then the discount position is missing.

Magento: v2.2.6, 
module: 2.4.0

**Comment by domeglic** [comment]
[This](https://github.com/PAYONE-GmbH/magento-2/blob/v2.4.0/Model/Api/Invoice.php#L219) condition is false when a discount without a coupon is used.  
`$oOrder->getCouponCode()` should probably be removed from that condition entirely.

**Comment by hreinberger** [comment]
Seems like this should have been fixed by #207 can you confirm this @domeglic ?

**Comment by domeglic** [comment]
Yes that does fix it. But the version I use is from git tag 2.4.0 so this was not included. But this issue can be closed as it is actually resolved
