### ISSUE TITLE
Wrong implementation with bank data in mails for advance payment

### ISSUE THREAD

**Issue by fischamhaken** [PAYONE-GmbH/magento-2#138]
Since version 1.3.5, the function "Bank Data now added to order confirmation email per default" has been added.

I believe that this is not usable as implemented now.

First, its ok to give the customer the hint for bank data to transfer his money. But: It should be possible to add custom notices for that. Translation file with "Please transfer the order amount to this bank account:" is fix and will be overwritten with updates. So it needs to have a custom field for this in Backend. For me, I would like to include the term of payment in this sentence.

Second, the shown Bank Data fields should be configurable. For example, for me, it should not include the account number, only IBAN! But this Block is fix an cannot be configured. So I cant use it. But I cannot disable it, because its set as default for advance paiment.

Btw: the translation of "Bank code:","Postleitzahl:" is wrong.

Third: It's very ok to add Bank data to order confirmation mail, but it's wrong to add bank data to invoice mail! (Escpecially with hint "Please transfer the order amount ....") - because there is a danger that the customer will remit once again!

There should either be another hint like "We have reveived your payment on our account xyz..." or it should be simply left - I have the possibility to notice customer via the customized mail.

And finally, in Creditmemos bank data should also not be displayed.

Please consider in implementations after all - whether the process is really useful?

Best regards,
Stefan

**Comment by fjbender** [comment]
Thanks for your feedback. I agree, the implementation as it is is not very useful. We had the urgent requirement to add the bank data at all, so it was done without regard for some useful additions.

We'll need some time, but will get back to it and improve with your suggestions.

**Comment by fischamhaken** [comment]
Hi Florian,

thank you for your quick feedback. :-)
Such things are a pity, because they bring the developer in dilemmas. 
In my case, I must now consider whether I upgrade or not and then have to program an exception to the exception.... always at the risk that the next upgrade the functionality changes again and I have to hand again.

But I'm just waiting hopefully.

Best regards,
Stefan
