### ISSUE TITLE
Alter module so that it can be used in a request free context

### ISSUE THREAD

**Issue by sydekumf** [PAYONE-GmbH/magento-2#141]
We use your module in several Magento instances of our customers. As we have complex requirements which make it necessary to trigger captures/debits etc on command line automatically and NOT in the backend manually, the module should be changed.

There are many places in the code where the module **expects** a backend context. For example, it is not possible to reset the Base request class and its parameters: https://github.com/PAYONE-GmbH/magento-2/blob/master/Model/Api/Request/Base.php

Also right before sending the request to Payone the credential parameters get overwritten by non-global configurations, but if you re-use the class it can not be re-initiated, as the `initRequest()` function is protected. So please make the module independent from any backend or request context, which makes our life easier as we do not have to overwrite so much classes of the module :-) Or at least change the functions to public or give the classes the functionality to re-initiate. Thanks :-)

**Comment by fjbender** [comment]
I think we have already discussed a similar topic in #92, with this ticket being the more generic one. We have added #92 to our backlog already and will take a look at it :)

**Comment by sydekumf** [comment]
Okay, that sounds great :-)
