### ISSUE TITLE
Partial capture of an order of 2 simples of the same configurable is wrong

### ISSUE THREAD

**Issue by sydekumf** [PAYONE-GmbH/magento-2#142]
**Precondition:**
- Place an order with 2 simples of one configurable (i.e. T-Shirt with two sizes)
- Create an invoice in the backend with **one** of the two products

**Expectation**
- An Invoice/Capture with exact this **one** product is made

**Actual result**
- The Payone module tries to capture both simples, and of course this throws an 1610 - Wrong article list error

**Explanation**
- ```Payone\Core\Model\Api\Request\Capture::getInvoiceList()``` builds an positions array with `configurable product id => qty`
- ```Payone\Core\Model\Api\Invoice::addProductItem()``` checks if every order item is in the positions array, but it checks it in a wrong way: It checks again the configurable product id. For 2 simples of the same configurable, this is true for both simples, but only one should have been invoiced/captured.

Info: This exact same problem also ocurres for debits (Gutschriften).

**Comment by fjbender** [comment]
This possibly duplicates #121
