### ISSUE TITLE
Support HTTP X-Forwarded-For Header

### ISSUE THREAD

**Issue by niclashoyer** [PAYONE-GmbH/magento-2#143]
The Magento 2 extension currently does not support the `X-Forwarded-For` header. We run our Magento 2 installations behind a reverse proxy and as such the IP that the extension uses is always `127.0.0.1`. It is currently not possible to receive transaction status messages. We'll add `127.0.0.1` to the allowed IPs as a workaround.

**Comment by fjbender** [comment]
@niclashoyer Can you confirm #145 fixes this issue?
