### ISSUE TITLE
Show speaking error messages if fields are not filled out correctly

### ISSUE THREAD

**Issue by fischamhaken** [PAYONE-GmbH/magento-2#150]
Hi together,

with M2.1.7 and Payone Extension 1.3.5 I have following issue:
If csutomer steps through checkout and fills in incoorect address values, the following message appears:
"An error occured on the server. Please try to place the order again"
In Payone API protocol I can see the problem, i.e. customer has filled field "Company" with "-".
Then Payone send back custom error message:

customermessage | Ungültiger Firmenname. Bitte überprüfen Sie die Angaben.
-- | --
1303
Parameter {company} faulty or missing

Unfortunately, this is not displayed to the customer, but it should be done so.

Greetings,
Stefan
![checkout](https://user-images.githubusercontent.com/30490386/36146421-de7e2a10-10b4-11e8-9808-ebdc72f66e7d.png)

**Comment by fjbender** [comment]
In theory, we already pass on the customer message: https://github.com/PAYONE-GmbH/magento-2/blob/master/Model/Methods/PayoneMethod.php#L119

I suppose the error message is generic due to a missing translation?
