### ISSUE TITLE
Error 1611 - Capturing when id contains an slash '/'

### ISSUE THREAD

**Issue by petertroeger** [PAYONE-GmbH/magento-2#152]
Can someone confirm this?

How to reproduce:

1. Create product with an id containing a / i.e. 'CD23445-white/blue'
2. Try to submit the invoice (send a capture to Payone)

Error: 1611
Parameter {id[n]} faulty or missing

Plugin Version 1.3.6
Magento 2.1.10

**Comment by fjbender** [comment]
@petertroeger can you tell me date, time and Merchant ID for this request in a message to integrations@bspayone.com? Thanks!

**Comment by fjbender** [comment]
The / was not the issue here, SKU was too long for the id[n] field.
