### ISSUE TITLE
Wrong amount/currency, if display currency not equal to base currency

### ISSUE THREAD

**Issue by josefbehr** [PAYONE-GmbH/magento-2#157]
If, for a website in Magento2, the base and display currency differ like here
![screen shot 2018-03-07 at 11 55 30](https://user-images.githubusercontent.com/4368880/37088734-a9fa1cda-21fe-11e8-8fbf-ccbdb5976f25.png)

then the capture/authorization request sent to PAYONE is sent using the amount in base currency (eg EUR), but the currency symbol used for the order (eg SEK), such that a wrong amount is invoiced!
![payone-sek-fehler](https://user-images.githubusercontent.com/4368880/37088850-ef3cb4ec-21fe-11e8-8acc-6aea7b1d758e.JPG)

Here is the corresponding code in "Model/Api/Request/Capture.php" and ".../Authorization.php": 
![screen shot 2018-03-07 at 11 56 00](https://user-images.githubusercontent.com/4368880/37088732-a9c2864e-21fe-11e8-971c-a39b56a0944a.png)
![screen shot 2018-03-07 at 11 55 49](https://user-images.githubusercontent.com/4368880/37088733-a9e14d54-21fe-11e8-91d6-506ca3f2a71e.png)

Please fix this to either send base currency symbol always, or convert amount to currency used in the order!

**Comment by fjbender** [comment]
This is definitely a bug. We'll fix it so that the base currency is used for all payment operations (as defined by Magento).

**Comment by ostukalovprovectus** [comment]
We're facing the same issue. However, we have a use case, when for the main store we have PLN, but another store view will show the same products converted in EUR (base currency PLN, prices displayed in EUR). And for this store view the charge should happen in EUR. Please advise.

**Comment by fjbender** [comment]
Okay, so what we'd need is a configuration option where the merchant is able to choose on a per-storeview basis whether they want to charge using base currency or display currency, right?

**Comment by ostukalovprovectus** [comment]
Exactly. How do you think, how much time can take this fix? As we're going live and it's blocking us atm.

**Comment by fjbender** [comment]
I can't tell exactly right now, but I suppose we'll need at least two week due to high developer load, sorry. However, you're always welcome to support us with PRs.

**Comment by josefbehr** [comment]
@fjbender @ostukalovprovectus 
I just created a pull request that addresses the issue: https://github.com/PAYONE-GmbH/magento-2/pull/159

**Comment by fjbender** [comment]
I tested the PR and I am still encountering problems concerning the item list. The currency configuration is not handled there; articles are always transmitted in the Display Currency while shipping is always transmitted as Base Currency, which leads to an inconsistent cart. We're looking into this.
