### ISSUE TITLE
Environment emulation nesting is not allowed

### ISSUE THREAD

**Issue by steros** [PAYONE-GmbH/magento-2#161]
> [2018-03-12 11:39:28] main.ERROR: Eine Verschachtelung der Umgebungs-Emulation ist nicht erlaubt. [] []

I get this obscure error pretty often and hope someone might have encountered it too?
As far as I can see this is thrown as `Environment emulation nesting is not allowed` in `app/code/Magento/Store/Model/App/Emulation.php:startEnvironmentEmulation()`.
Which up the code is triggered from emailing. Which in my magento setup only happens through the payone plugin when invoicing.

**Comment by fjbender** [comment]
Just by `grep`ing through the code I'd say we don't use `startEnvironmentEmulation()` anywhere. Maybe it's caused by some race condition? Or does it happen systematically for all payone invoicing emails?

**Comment by steros** [comment]
if, you don't use it directly.
startEnvironmentEmulation() is called in:
- app/code/Magento/Email/Model/AbstractTemplate.php:applyDesignConfig()
- **app/code/Magento/Payment/Helper/Data.php:getInfoBlockHtml() which does: "Render payment information block"**
- app/code/Magento/ProductAlert/Model/Email.php:send()

Especially the second one made me think, it might be related to the plugin.
