### ISSUE TITLE
site down after install

### ISSUE THREAD

**Issue by Annie-Mi** [PAYONE-GmbH/magento-2#166]
Warning: PDOStatement::execute(): MySQL server has gone away in vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228

**Comment by fjbender** [comment]
I'm not sure if this error is related to the module alone. There seems to be a problem with the database server.

**Comment by Annie-Mi** [comment]
![screenshot 1](https://user-images.githubusercontent.com/16383595/38557553-62b2be9c-3c9b-11e8-8dc9-a97c046d3b80.jpg)

**Comment by fjbender** [comment]
Can you upload the stacktrace again in plain text with the MySQL credentials removed? Thanks.

**Comment by Annie-Mi** [comment]
yes, of course.
thank you for the help

If I enable the module and do the upgrade command I'm getting immediately an error:
the last line is:
Module 'Payone_Core':
Installing data... Warning: PDOStatement::execute(): MySQL server has gone away in /vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228


than if I check the site, it is gone:
> PDOException: SQLSTATE[HY000] [2002] No such file or directory in ../vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:128 Stack trace: #0 ../vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(128): PDO->__construct('mysql:host=loca...', 'd028d301', 'qUQn4uKDrJ4hgRz...', Array) #1 ../vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect() #2 ../vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(398): Zend_Db_Adapter_Pdo_Mysql->_connect() #3 ../vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(861): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect() #4 ../vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(931): Zend_Db_Adapter_Abstract->quote('0', NULL) #5 ../vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(1437): Zend_Db_Adapter_Abstract->quoteInto('log_id = ?', '0', NULL, NULL) #6 ../vendor/magento/zendframework1/library/Zend/Db/Select.php(1031): Magento\Framework\DB\Adapter\Pdo\Mysql->quoteInto('log_id = ?', '0', NULL) #7 ../vendor/magento/zendframework1/library/Zend/Db/Select.php(496): Zend_Db_Select->_where('log_id = ?', '0', NULL, true) #8 ../vendor/magento/framework/DB/Select.php(119): Zend_Db_Select->where('log_id = ?', '0', NULL) #9 ../vendor/magento/framework/EntityManager/Db/ReadRow.php(54): Magento\Framework\DB\Select->where('log_id = ?', '0') #10 ../vendor/magento/framework/EntityManager/Operation/Read/ReadMain.php(63): Magento\Framework\EntityManager\Db\ReadRow->execute('Mirasvit\\Search...', '0') #11 ../vendor/magento/framework/EntityManager/Operation/Read.php(108): Magento\Framework\EntityManager\Operation\Read\ReadMain->execute(Object(Mirasvit\SearchReport\Model\Log), '0') #12 ../vendor/magento/framework/EntityManager/EntityManager.php(70): Magento\Framework\EntityManager\Operation\Read->execute(Object(Mirasvit\SearchReport\Model\Log), '0', Array) #13 ../vendor/mirasvit/module-search-report/src/SearchReport/Repository/LogRepository.php(60): Magento\Framework\EntityManager\EntityManager->load(Object(Mirasvit\SearchReport\Model\Log), '0') #14 ../vendor/mirasvit/module-search-report/src/SearchReport/Service/LogService.php(74): Mirasvit\SearchReport\Repository\LogRepository->get('0') #15 ../vendor/mirasvit/module-search-report/src/SearchReport/Plugin/ResponsePlugin.php(96): Mirasvit\SearchReport\Service\LogService->logClick('0') #16 ../vendor/magento/framework/Interception/Interceptor.php(121): Mirasvit\SearchReport\Plugin\ResponsePlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor)) #17 ../vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Response\Http\Interceptor->Magento\Framework\Interception\{closure}() #18 ../generated/code/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array) #19 ../vendor/magento/framework/App/Http.php(185): Magento\Framework\App\Response\Http\Interceptor->sendResponse() #20 ../vendor/magento/framework/App/Http.php(156): Magento\Framework\App\Http->handleDeveloperMode(Object(Magento\Framework\App\Bootstrap), Object(Zend_Db_Adapter_Exception)) #21 ../vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->catchException(Object(Magento\Framework\App\Bootstrap), Object(Zend_Db_Adapter_Exception)) #22 ../index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http)) #23 {main} Next Zend_Db_Adapter_Exception: SQLSTATE[HY000] [2002] No such file or directory in ../vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:144 Stack trace: #0 ../vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect() #1 ../vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(398): Zend_Db_Adapter_Pdo_Mysql->_connect() #2 ../vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(861): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect() #3 ../vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(931): Zend_Db_Adapter_Abstract->quote('0', NULL) #4 ../vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(1437): Zend_Db_Adapter_Abstract->quoteInto('log_id = ?', '0', NULL, NULL) #5 ../vendor/magento/zendframework1/library/Zend/Db/Select.php(1031): Magento\Framework\DB\Adapter\Pdo\Mysql->quoteInto('log_id = ?', '0', NULL) #6 ../vendor/magento/zendframework1/library/Zend/Db/Select.php(496): Zend_Db_Select->_where('log_id = ?', '0', NULL, true) #7 ../vendor/magento/framework/DB/Select.php(119): Zend_Db_Select->where('log_id = ?', '0', NULL) #8 ../vendor/magento/framework/EntityManager/Db/ReadRow.php(54): Magento\Framework\DB\Select->where('log_id = ?', '0') #9 ../vendor/magento/framework/EntityManager/Operation/Read/ReadMain.php(63): Magento\Framework\EntityManager\Db\ReadRow->execute('Mirasvit\\Search...', '0') #10 ../vendor/magento/framework/EntityManager/Operation/Read.php(108): Magento\Framework\EntityManager\Operation\Read\ReadMain->execute(Object(Mirasvit\SearchReport\Model\Log), '0') #11 ../vendor/magento/framework/EntityManager/EntityManager.php(70): Magento\Framework\EntityManager\Operation\Read->execute(Object(Mirasvit\SearchReport\Model\Log), '0', Array) #12 ../vendor/mirasvit/module-search-report/src/SearchReport/Repository/LogRepository.php(60): Magento\Framework\EntityManager\EntityManager->load(Object(Mirasvit\SearchReport\Model\Log), '0') #13 ../vendor/mirasvit/module-search-report/src/SearchReport/Service/LogService.php(74): Mirasvit\SearchReport\Repository\LogRepository->get('0') #14 ../vendor/mirasvit/module-search-report/src/SearchReport/Plugin/ResponsePlugin.php(96): Mirasvit\SearchReport\Service\LogService->logClick('0') #15 ../vendor/magento/framework/Interception/Interceptor.php(121): Mirasvit\SearchReport\Plugin\ResponsePlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor)) #16 ../vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Response\Http\Interceptor->Magento\Framework\Interception\{closure}() #17 ../generated/code/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array) #18 ../vendor/magento/framework/App/Http.php(185): Magento\Framework\App\Response\Http\Interceptor->sendResponse() #19 ../vendor/magento/framework/App/Http.php(156): Magento\Framework\App\Http->handleDeveloperMode(Object(Magento\Framework\App\Bootstrap), Object(Zend_Db_Adapter_Exception)) #20 ../vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->catchException(Object(Magento\Framework\App\Bootstrap), Object(Zend_Db_Adapter_Exception)) #21 ../index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http)) #22 {main}

**Comment by Annie-Mi** [comment]
it has a problem with mirasvit search plugin. We'd need both plugins. how to fix it?
Thank you

**Comment by fjbender** [comment]
As the plugin isn't available on Github, I can't file a bug report with them. Maybe someone from Mirasvit can help here and point out what's wrong.

I suppose you have some kind of support contact to them? Maybe you can point them here to tell us what went wrong.
