### ISSUE TITLE
Addresscheck is not working for addresses from the addressbook

### ISSUE THREAD

**Issue by juules** [PAYONE-GmbH/magento-2#167]
Hi together,

with M2.1.12 and Payone Extension 2.0.2 I have the following issue in the checkout:

When the customer is choosing an existing shipping address out of his addressbook instead of a new address there is no addresscheck like adding a missing whitespace between the street and house number.

Steps to reproduce:
- Go to the addressbook in the customer account 
- Add a new shipping address and do not add an whitespace between the street and housenumber (e.g. "Musterstraße12")

- Go to the checkout
- Add a new shipping address and do not add an whitespace between the street and housenumber (e.g. "Musterstraße12")
- The addresscheck will notice this and change it correctly to "Musterstraße 12"

- Now choose the wrong address from the addressbook instead of adding a new one
- There will be no addresscheck and the order get processed with the wrong address

Is there a possibility to process the complete addresscheck also to existing addresses from the addressbook and also save the corrected address afterwards in the customer account?

Thank you in advance!
Julia

![checkout](https://user-images.githubusercontent.com/3296118/38504016-e1eda6d2-3c13-11e8-99b1-38469e874d7c.png)

**Comment by fjbender** [comment]
Thanks for your feedback. I could reproduce this issue.

My intention is to fix it in a way that "unchecked" addresses are checked during checkout (to prevent the customer from adding a zillion addresses and triggering an address check each time) and the corrected address is saved back to the database. Then, if the address is used again at a later time, the corresponding lifetime setting is checked to determine whether the address has to be checked again.

**Comment by juules** [comment]
Thank you for your quick answer. 
Your way to fix this problem sounds really good. Until when do you think this issue can be fixed? Our client has a lot of trouble with wrong addresses and would need this fix as soon as possible.

**Comment by juules** [comment]
Okay. Please just inform me when you have more information.

**Comment by fjbender** [comment]
@juules we're still working on this, it turned out to be a little more complicated than initially thought.
