### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by brenohalabi** [PAYONE-GmbH/magento-2#175]
Hi there.

I need to send to payone a notification for order cancelation. As I've looked, the module is not handling it. Am I right?

Is there a API documentation for customize it?

Thanks.

**Comment by fjbender** [comment]
Hi

unfortunately, there is no technical documentation for the module itself. For the Payone-API there is an API description, of course.

From scratch, you'd need to hook up to the "cancel" button and then construct a capture request with the amount=0.

**Comment by brenohalabi** [comment]
Hi. Thanks for answer.

Can you share Payone-API?

**Comment by fjbender** [comment]
I sent you an email.
