### ISSUE TITLE
setup:di:compile Problem

### ISSUE THREAD

**Issue by dh1984** [PAYONE-GmbH/magento-2#18]
We get on setup:di:compile in the developer mode following error message:

Repositories code generation... 1/7 [====>-----------------------]  14%
1 sec 77.8 MiBPHP Fatal error:  Cannot use Magento\Framework\Controller\Result\Redirect as Redirect because the name is already in use in /xxx/vendor/payone-gmbh/magento-2/Controller/Onepage/Cancel.php on line 30

**Comment by fjbender** [comment]
Can't reproduce :(
```
florian@charon:/var/www/html/shops/magento2/current$ php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
florian@charon:/var/www/html/shops/magento2/current$ php bin/magento deploy:mode:set developer
Enabled developer mode.
florian@charon:/var/www/html/shops/magento2/current$ php bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 7/7 [============================] 100% 2 mins 244.0 MiBBB MiB
Generated code and dependency injection configuration successfully.
```

The only thing I can imagine being a problem is the name collision of the classes `\Magento\Framework\Controller\Result\Redirect` and `\Payone\Core\Controller\Onepage\Redirect` (which shouldn't be a problem at all).

Does the error still occur with eed151e45d0823b67c9e1ed32dd1053a70a049b5 applied?

**Comment by dh1984** [comment]
That solves the error.
