### ISSUE TITLE
Missing Documentation for M2 Payone Extension

### ISSUE THREAD

**Issue by andidhouse** [PAYONE-GmbH/magento-2#180]
For magento1 there is a documentation you can download here (right side):
https://www.payone.com/plattform-integration/extensions/magento/

For magento2 there is no such documentation:
https://www.payone.com/plattform-integration/extensions/magento2/

Where do we find for example the TransactionStatus URL which is needed for the payone portal?
etc.

Thanks

**Comment by fjbender** [comment]
The transaction status URL is https://youshop.host/payone/Transactionstatus/Index

Please find attached a preliminary version of the documentation, which will be uploaded to the website soon: 
[PAYONE Payment Integration für Magento 2.0-v18-20180621_0817.pdf](https://github.com/PAYONE-GmbH/magento-2/files/2122371/PAYONE.Payment.Integration.fur.Magento.2.0-v18-20180621_0817.pdf)

**Comment by fjbender** [comment]
In theory, both should work (the IndexAction should be the default one anyway). To be safe, you should use the URL ending in /Index. I'll fix the documentation accordingly.
