### ISSUE TITLE
Major issue in order process handling / event triggers

### ISSUE THREAD

**Issue by andidhouse** [PAYONE-GmbH/magento-2#182]
Hi there,

there is a major issue when installed your extension on a clean system with the handling of order events.

Your extension "blocks" the internal magento order events which are used by many other extensions like mirasvit follow up email or web cooking ecommerce tracking (server side).

It seems that the payone extension somehow "blocks" or "removed" these native magento events totally. For example you can not trigger emails any more by order status or any order event.

This is a major issue as every ecommerce system uses these events for marketing, analytics etc. etc.
It is tested on two different systems (different servers and server setups) and it is related to the payone extension. If you run the other other extensions there is no problem - if payone is installed no events can be triggered any more.

Can you pls let us know 

- a) what a quick fix is possible here
- b) why your extension is blocking these events for other extensions?
and finally 
- c) when this is planned to fix in a stable version

If you have any questions regarding the issue pls do not hesitate to contact me here.

Thanks

**Comment by fjbender** [comment]
We have to rewire some of the events to delay for instance order confirmation e-mails, for instance to make sure that an order confirmation e-mail only gets send out when the customer completes a third party checkout (e.g. PayPal or Sofort). However, I'd expect things to continue smoothly from there.

Can you point me to an example event so I can trace where we possibly block it?

Thanks

**Comment by andidhouse** [comment]
Hello Florian,

thanks for your quick reply.
One event for example is the "invoice created" event. This is for example used in the mentioned ecommerce extension from extension supplier webcooking.

Pls see the screen attached (screen1).

Before installing payone this works without a problem - after install nothing is transmitted any more.

Another event is for example the "sales / order status was changed" or "order obtained" event used by mirasvit follow up (screen2).

Thanks!
![2](https://user-images.githubusercontent.com/16196483/41722047-b826f30c-7567-11e8-9abd-4c43daf80d6e.png)
![1](https://user-images.githubusercontent.com/16196483/41722048-b8451e04-7567-11e8-8aa1-c5e288648a45.png)

**Comment by fjbender** [comment]
Sorry for the delay in analyzing this. However, we couldn't find any issues. Our developers wrote a test module to consume the same events and it worked smoothly. Can we rule out that there's an incompatibility in the plugin you're using?

**Comment by hreinberger** [comment]
closing this due to non-activity. If this is still an issue, please re-open or create a new one.
