### ISSUE TITLE
After upgrade no any payment method working

### ISSUE THREAD

**Issue by D-David11** [PAYONE-GmbH/magento-2#183]
Hello, I was using your payone(2.0.2) in my magento(2.1.10) all were working well, but after upgrade payone version(2.2.1) all method get stop working. 

I have downloaded the payone from here and overwrite the folder but now I am getting different error in all payment method in test mode.

Error #1 1077 - Expiration date invalid. Please check the information on the map. (by creditcard)
Error #2 An error occurred while processing this transaction (wrong parameters). (by paypal,sofort)

If i downgrade the payone version then all working well. Can you please help me on that.

**Comment by fjbender** [comment]
Hi @D-David11, I'd advise you contact our Technical Support Team first. They'll be able to troubleshoot most problems concerned with updates.

Also please make sure you follow the standard Magento 2 upgrade procedure (installing/upgrading the module through composer, then running setup:upgrade from the Magento console etc.).

**Comment by D-David11** [comment]
Hello fjbender,

Yes, I have followed the magento standard and fire following command.
->php bin/magento setup:upgrade
->php bin/magento setup:static-content:deploy
->php bin/magento cache:clean
->php bin/magento cache:flush

I am the technical person, I have checked all the files to resolved but with no luck. when I restore old version all is working well but in new version no any payment method working. So the bug must be in new version.

I am getting followin error in every payment method.

Error #1 1077 - Expiration date invalid. Please check the information on the map. (by creditcard) // even the date is greater then current year
Error #2 An error occurred while processing this transaction (wrong parameters). (by paypal,sofort)

**Comment by fjbender** [comment]
Have you run `php bin/magento setup:di:compile` after `php bin/magento setup:upgrade`?

If yes, please contact our Technical Support Team so they can open an internal ticket with me. I'm not yet convinced this is a bug in the module.

**Comment by D-David11** [comment]
Hello, 

Can you share the link or email of your support team ?

**Comment by fjbender** [comment]
Sure, you can use the form at https://www.payone.com/kontakt/support/ or just call them at +49 431 25968-500.
