### ISSUE TITLE
order confirmation email not getting sent

### ISSUE THREAD

**Issue by IIxauII** [PAYONE-GmbH/magento-2#193]
Since I have added PayOne to my Magento2 store the order confirmation emails are not getting sent anymore.
I checked the mail logs but there are no error's, the mail doesn't get sent at all.
All other mail sending requests work (forgot password / manually sending order confirmation etc)
Could it be that the payment gateway is the issue here? skipping the mail sending process/not triggering the event?

**Comment by fjbender** [comment]
Our module blocks order confirmation emails and sends them once the asynchronous notification about successful initiation of payment is received. This is to prevent order confirmation emails being send for orders that have not been completed on e.g. PayPal's side.

For this to work, please make sure that the notification URL ("Transaction Status URL") is set in the Payone Merchant Interface for the payment portal you're using. The schema is `https://yourshop/index.php/payone/transactionstatus` if Magento 2 is available in the root.

**Comment by IIxauII** [comment]
Thx for the information.
Is there an easy way to still get order confirmations for payment methods like:
* Payment in advance
* cash on delivery
* bill
Since currently I am not getting any order confirmations for those payment methods and have to send them manually

**Comment by fjbender** [comment]
Those should be triggered by the same notification mechanism. If you don't get any order confirmation emails, can you check whether the transaction status notification is received? It should show up in the Transaction Status Log in the backend.

**Comment by IIxauII** [comment]
any update on this ?

**Comment by IIxauII** [comment]
Could it maybe be that I setup cronjob wrongs ? Is there a special cronjob for payone emails or something ?

**Comment by omargits** [comment]
Order emails not transmitted. I am using Magento 2.3.3 Payone module version 2.7.0 
from 
Protocol - TransactionStatus
its **appointed**  and then **paid** but still upto now no email. Magento cron is working fine.
on Server varnish 5.01. from above you said return url must be 
**website.com/payone/transactionstatus**
returns **Access denied**
please guide us what to do

**Comment by hreinberger** [comment]
Hi, so an Access Denied can occur for many reasons, mostly it's a faulty URL or some kind of webserver config issue. I think it'd be best if you contact our technical support team. You can find the full contact details here (in the right column): https://docs.payone.com/display/public/PLATFORM/Contact

**Comment by omargits** [comment]
as technical guys from payone say its fine. payment status are changing from appointed to payed but still no email yet

**Comment by mageconsult** [comment]
There is a bug in Magento 2.3.3. sending emails with non-ascii values in sender name (umlauts, accents). Maybe it is a side effect, that this error occurs.
