### ISSUE TITLE
Problems with order paid event since 2.3.0

### ISSUE THREAD

**Issue by niclashoyer** [PAYONE-GmbH/magento-2#199]
In the [`Observer/Transactionstatus/Paid.php`](https://github.com/PAYONE-GmbH/magento-2/blob/master/Observer/Transactionstatus/Paid.php#L79) the inline documentation states:

         * Generate an invoice for the order to mark the order as paid

but it seems that with the changes in #164 released in 2.3.0 the invoices are no longer generated. We've got an extension that does something if the order gets paid, so it listens to the `sales_order_invoice_pay` event.

If there is no invoice generated now, how can we detect if the order is paid?

Might be related to #182.

**Comment by fjbender** [comment]
We are a little bit overdue for a release, indeed, as we're waiting for a larger feature. However, we can squeeze in a smaller release soon to make the bugfixes available to all.
