### ISSUE TITLE
list on packagist.org

### ISSUE THREAD

**Issue by davidverholen** [PAYONE-GmbH/magento-2#2]
would it be possible to list the extension on https://packagist.org for easier installation? I see you already have an extension there. https://packagist.org/packages/payone-gmbh/

**Comment by fjbender** [comment]
Yes, absolutely. I'm on this.

**Comment by fjbender** [comment]
@davidverholen can you verify it's working now? Submitted the package to Packagist, but I'm unsure about real world usage: https://packagist.org/packages/payone-gmbh/magento-2

**Comment by davidverholen** [comment]
the 1.2.2 release is not listed on packagist. I think it's because of the name change (that release still has the old composer name).

You could either create a new bugfix release (1.2.3), which would be semver compliant or create a patch release (for example 1.2.2-patch1).

Another possibility would be to delete the 1.2.2 release and recreate it on the last commit of the master branch. Normally, you would not want to do this, but since this package pretty sure is not in production use anywhere right now I think it's ok

**Comment by fjbender** [comment]
@davidverholen pushed the v1.2.3 release which is being shown on Packagist now.

**Comment by davidverholen** [comment]
thank you very much, this should be it. I just found another issue installing it on magento 2.1 (if 2.1 is supported already)
