### ISSUE TITLE
Payment details not align in order confirmation email in Outlook

### ISSUE THREAD

**Issue by marta-siew** [PAYONE-GmbH/magento-2#200]
In an order confirmation email for Outlook 2016 / Office 365 payments details are shifted to the right and not align. Please consider fixing it as Magento 2 should support Outlook: https://devdocs.magento.com/guides/v2.0/frontend-dev-guide/templates/template-email.html

![zrzut ekranu 2018-08-31 o 10 42 06](https://user-images.githubusercontent.com/42863272/44904209-ddf88800-ad0e-11e8-9f4c-c1a1ea6ec621.png)

**Comment by hreinberger** [comment]
closing this due to non-activity. If this is still an issue, please re-open or create a new one.
