### ISSUE TITLE
Shipment email uses backend locale.

### ISSUE THREAD

**Issue by mfickers** [PAYONE-GmbH/magento-2#203]
The payment info block in the shipment emails is not translated into the frontend locale properly. I'm sending the emails via backend, but shipment emails should always be considered frontend so I think this is a bug.

German frontend, English backend:
![bildschirmfoto 2018-09-10 um 16 37 24](https://user-images.githubusercontent.com/12683535/45304411-597ce500-b518-11e8-87c7-0ccf2913b631.png)

German frontend, German backend:
![bildschirmfoto 2018-09-10 um 16 41 03](https://user-images.githubusercontent.com/12683535/45304412-597ce500-b518-11e8-83f5-0c8c96ea3129.png)

Magento ver. 2.1.12
Payone_Core ver. 2.2.0

**Comment by fjbender** [comment]
I'm not entirely sure this is within the realm of our module. As far as I see it, we're using the `__` wrapper which should take care of selecting the right locale.

**Comment by hreinberger** [comment]
closing this due to non-activity. If this is still an issue, please re-open or create a new one.
