### ISSUE TITLE
2.3 - Problems with telephone number and validation in payment method Klarna

### ISSUE THREAD

**Issue by chris-exu** [PAYONE-GmbH/magento-2#205]
Problem 1: Klarna seems to require a valid telephone number for every order, otherwise you get an error message „Wrong parameters“ (Bei der Bearbeitung dieser Transaktion ist ein Fehler aufgetreten (Falsche Parameter).). The problem is, when telephone is set to optional in the customer configuration, and the customer has not entered it, it’s not possible to pay via Klarna because the additional input field for the telephone is not shown in the template (payone-gmbh/magento-2/view/frontend/web/template/payment/klarna.html). The field is shown when the file payone-gmbh/magento-2/view/frontend/web/js/view/payment/method-renderer/klarna-method.js is overridden in the custom theme, and the if-condition on row 62 is changed like this:

requestTelephone: function () {
if (this.getBillingCountry() !== false && this.telephone() != '') {
return false;
}
return true;
},
In that case the field is shown on when the page loads but disappears as soon as you enter anything - it’s removed entirely from the HTML source code. It’s still not possible to confirm the order using Klarna, so the user just hangs there with the non-informative error message „Wrong parameters“. 

Problem 2: klarna-method.js is missing validation for telephone number, as well as gender and birthday which are all required parameters for Klarna. Only the agreements for data processing through Klarna are validated. If any of these required parameters are missing and the user tries to pay, they only see the very uninformative error message „Wrong parameters“ (Bei der Bearbeitung dieser Transaktion ist ein Fehler aufgetreten (Falsche Parameter).). Additional validation therefore needs to be added for telephone, gender and birthday.

**Comment by lastralab** [comment]
@chris-exu were you able to fix it?
I'm having the same problem, not sure how to avoid that exception.
