### ISSUE TITLE
Transaction status received/processed multiple times

### ISSUE THREAD

**Issue by niclashoyer** [PAYONE-GmbH/magento-2#208]
We've got a strange issue regarding transaction status. On some orders the "appointed" and/or "paid" transaction status messages are processed twice (with a delay of about an hour). According to Payone support they just sent *one* message and the shop answered with `TSOK`.

In the backend we see this in the order comments:
![bildschirmfoto von 2018-10-11 10-42-12](https://user-images.githubusercontent.com/175808/46791879-560c9180-cd42-11e8-88cd-249ac8759d05.png)

According to Payone the system just sent the appointed message on `2018-10-09 21:31:21` for this transaction id:

![bildschirmfoto von 2018-10-11 10-45-11](https://user-images.githubusercontent.com/175808/46792086-c5828100-cd42-11e8-8ad9-83615b1e2f86.png)

I'm a bit lost here, as I don't know how to debug this further.

**Comment by niclashoyer** [comment]
We are currently monitoring the response of the shop to the transaction messages, so we can better understand what is happening if it fails again. I'll reopen if we find something.

**Comment by omargits** [comment]
@niclashoyer  can you please share ur findings where exactly was issue. bcz we having same kind of issue on our shop. In our case Appointed status is two time and also two invoices created one is with 0.00 and other with correct amount.

please do share your findings for this issue

thanks

**Comment by niclashoyer** [comment]
@omargits 

In our case it was an Observer on the order status that should trigger an order export after the order has been paid. This observer throwed an exception *after* the Payone extension answered. But in your case it might be different.

**Comment by omargits** [comment]
@niclashoyer  any idea how we can debug this. this is start happing 3-4 days ago. and in between there is no new extension installed nor any customization etc

please guide us
