### ISSUE TITLE
Problems with free order items / vouchers and PayPal

### ISSUE THREAD

**Issue by niclashoyer** [PAYONE-GmbH/magento-2#210]
We've got some failing requests with PayPal payment which seems to deny line items with zero price amount. The support told us that we either have to

 - send line items with price "0" as type "voucher"

or

 - do not send order items at all to PayPal

Is any of this configuration possible? I had a look in the configuration, but I did not find such settings.

**Comment by hreinberger** [comment]
Hi @niclashoyer 
if you don't use any payment methods which require sending the cart items you could deactivate this feature under PAYONE --> General

**Comment by hreinberger** [comment]
Hi again,
I dug a bit into the plugin and found this "hidden feature" 😄. If you disable the cart data globally (via the option above), payment methods which require cart data still send it. So even if you use our safe invoice you should be fine by disabling the cart data. 

I tested this with our safe invoice, Klarna and Paysafe Invoice, so you should do some testing with your specific payment methods, but it should work out of the box.

**Comment by niclashoyer** [comment]
Ah, okay, that wasn't really clear to us. We'll disable the transfer globally now and check the results. I'll reopen if something goes wrong.
