### ISSUE TITLE
Custom fields in PMI

### ISSUE THREAD

**Issue by niclashoyer** [PAYONE-GmbH/magento-2#212]
We have some custom fields on the order that our customer would like to have in Payone PMI for their accounting process.

Is there any possibility to send extra fields using the extension? Or maybe an event we could attach to? I don't know if it is possible to send extra fields via Payone API at all.

**Comment by hreinberger** [comment]
Hi @niclashoyer 
our API supports the individual parameter "param" for dynamic use, though this doesn't get shown in the merchant's PMI. You could change the behavior of existing parameters to show more info, for example by altering the "reference" parameter from showing the incrementId to something more suiting e.g. here: https://github.com/PAYONE-GmbH/magento-2/blob/4baaa8e5c1196b1acf56c844b99ee4ad1ae481cf/Model/Api/Request/Authorization.php#L151
However, please note that this parameter has to be unique and less than 20 characters. 

So to answer your question more specifically: There's no out-of-the-box way to send extra parameters and even if you get the extension to send one, it won't show in the PMI unless it's a parameter that already gets shown in there. :(

**Comment by niclashoyer** [comment]
Thank you for the quick response! I'll close this for now. The `ref_prefix` may be suitable.
