### ISSUE TITLE
creditcard checkbox

### ISSUE THREAD

**Issue by derendo** [PAYONE-GmbH/magento-2#220]
When entering CC number and forget to check the checkbox "Payone Creditcard" and then go on "buy now" ... nothing happens.... order doesn't get finished. So its a must to check the checkbox "Payone Creditcard" to finalize an order. Can this be coded in so that if someone enters a CC number the checkbox gets checked automated? Or is that fixed alsready in one of the releases? Thanks

**Comment by fjbender** [comment]
I'm not quite sure I understand which checkbox you mean. Can you maybe provide a screen shot?

**Comment by derendo** [comment]
If I don't click on checkbox "Payone Creditcard" and order system doesn't finish order. Only if its checked it finishes the order
<img width="243" alt="bildschirmfoto 2019-01-09 um 14 28 05" src="https://user-images.githubusercontent.com/46521030/50902403-1590e280-141b-11e9-9702-3882789d63f5.png">
So the way you see here it doesn't work

**Comment by derendo** [comment]
<img width="245" alt="bildschirmfoto 2019-01-09 um 14 41 04" src="https://user-images.githubusercontent.com/46521030/50902928-9f8d7b00-141c-11e9-9471-080c66bb64b8.png">
That way it works

**Comment by fjbender** [comment]
This is weird, because in the default template, the credit card input fields don't show up as long as the "Payone - Creditcard" radio button is not triggered.

**Comment by derendo** [comment]
yes that would make sense if they don't show up until the button is triggered.

**Comment by fjbender** [comment]
This is the default behavior. I would guess that your template somehow overrides this.
