### ISSUE TITLE
Problem bei Kreditkartenzahlung. Bestellungen trotz fehlerhafter Daten im Testmodus

### ISSUE THREAD

**Issue by espressobytes** [PAYONE-GmbH/magento-2#23]
**Zusammenfassung:**
Problem bei Kreditkartenzahlung: Bestellung wird abgeschickt, obwohl kein Vor- und/oder Nachname in den Kreditkarte angegeben ist.

**Details zur Reproduktion:**
- Payone mus im Testmodus sein
- Artikel in den Warenkorb legen
- zur Kasse gehen (bis Zahlungsart)
- Kreditkarte auswählen
- Kreditkarten-Daten eingeben, allerdings keinen Namen
- auf "Jetzt kaufen" klicken

**Aktuelles Verhalten**
- Es erscheint eine Fehlermeldung (Bitte Vornamen eingeben)
- Die Zahlung wird trotzdem abgeschlossen (User erhält Bestätigungsmail und wird auf Success-Seite weitergeleitet)

**Erwartetes Verhalten:**
- Fehlermeldung (Bitte Vornamen eingeben)
- Die Zahlung wird nicht abgeschlossen. User wird nicht weitergeleitet.

**Mögliche Ursache**
In der js-Datei credidcard-method.js wird zuerst die Funktion validate aufgerufen.
Das führt dazu, dass die Fehlermeldung "Bitte Vornamen angeben" erscheint.

Gleichzeitig wird aber über das iFrame ein ajax-call zu secure.pay1.de durchgeführt. In den Script (payone_hosted_min.js) wird dann wiederum in die Funktion
`processPayoneResponseCCHosted(response) `
(wieder in der Datei credidcard-method.js)
aufgerufen.

Obwohl die vorige Validierung (`validate: function`) vorher fehlgeschlagen ist, ist die response von Payone positiv:

In Zeile: 156: `if (response.status === "VALID") { ...}` => true

ist dieses Verhalten im Testmodus normal?

Trotzdem die Frage: Wieso führt man nicht in der Funktion processPayoneResponseCCHosted nochmal eine Validierung durch, um diesen Fall zu vermeiden.

z.B.:

```
function processPayoneResponseCCHosted(response)
{
    if (window.ccjs.firstname() != "" && window.ccjs.lastname() != "") {
        window.ccjs.processPayoneResponseCCHosted(response);
    }
}
```

**Comment by fjbender** [comment]
Danke für das detaillierte Feedback! Wir werden eine entsprechende Validierung einbauen.

@FATCHIP-GmbH go for it! :)

**Comment by fjbender** [comment]
Mit #29 gefixt.
