### ISSUE TITLE
Order items data send to Payone but not visible in Transaction details on PayPal

### ISSUE THREAD

**Issue by Neos2007** [PAYONE-GmbH/magento-2#235]
The problem that using PayPal payment via Payone, in PayPal account of the customer, on the transaction details page is not rendered ordered items data (in Order details table) which is usually available if the order was placed via Magento core paypal module.   
In Magento Payone module  configuration set Transmit Invoice Information to "Yes"
![image](https://user-images.githubusercontent.com/17883826/57531386-0034b200-7342-11e9-921e-42988a6654ae.png)

**Examples  details of transactions done with different payment modules.**
**Transaction via Payone:**
![image](https://user-images.githubusercontent.com/17883826/57530783-aa133f00-7340-11e9-92d3-2835c85b1593.png)
**Transaction via Magento Paypa:l**
![image](https://user-images.githubusercontent.com/17883826/57531060-4d645400-7341-11e9-93f7-660b9a3fdeba.png)

Environment: "payone-gmbh/magento-2": "2.3.0", Magento ver. 2.2.5

**Comment by fjbender** [comment]
Hi,
This should work, I can't reproduce this issue.
Can you specify one affected Payone Transaction ID?

**Comment by Neos2007** [comment]
Hi @fjbender.
Examples of  Payone Transaction IDs (different orders) : 332567101, 332564672, 332542252
All orders were created in sandbox mode.

**Comment by hreinberger** [comment]
Hi @Neos2007,
thanks for providing the IDs. I did some digging and found that your Shop is talking to our API the right way. The issue was in your merchant account. There was an ancient ignore_items flag active, which I just deleted. 
So any future tests should now show the cart items at PayPal. Could you try it once again?
