### ISSUE TITLE
Numbers in payone_protocol_transactionstatus must be stored as decimal

### ISSUE THREAD

**Issue by jakobmeissner** [PAYONE-GmbH/magento-2#241]
Price, balance and receivable in payone_protocol_transactionstatus are currently stored as floats. But money values should be stored as decimals to prevent rounding differences.

I currently have an issue where the Payone Platform correctly sends me a receivable of 23270.28,  but 
1) selecting this with mysql without explicitly casting it to decimal results in an incorrect value of 23270.3
2) the model itself, \Payone\Core\Model\Handler\TransactionStatus holds the incorrect value (checked this in the appointed callback observer)

**Comment by fjbender** [comment]
I think we have addressed this issue in #234. Can you still reproduce this with `dev-master`?

**Comment by jakobmeissner** [comment]
I did not check dev-master but since you changed the table columns, I'm confident It's done.
