### ISSUE TITLE
Update fails via Extension Manager

### ISSUE THREAD

**Issue by oliverf72** [PAYONE-GmbH/magento-2#245]
Hi, while updating we receive the following error:
Check Component Dependency
We found conflicting component dependencies. Hide detail

Command "require" failed: 
In ArtifactRepository.php line 61:

RecursiveDirectoryIterator::__construct(repo/): failed to open dir: No such 
file or directory 

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>...]

**Comment by fjbender** [comment]
Hi @oliverf72, 

It is recommended to user composer on the commandline, e.g. `composer update payone-gmbh/magento-2`.

If this doesn't work, please provide more details about your system environment, i.e. versions of Magento, PHP, Composer and our extensions, as well as the output of `composer -vv update payone-gmbh/magento-2`.

Thanks
Florian

**Comment by hreinberger** [comment]
closing this due to non-activity. If this is still an issue, please re-open or create a new one.
