### ISSUE TITLE
Plugins always call AddressCheck Ajax/WebApi

### ISSUE THREAD

**Issue by bjoern-flagbit** [PAYONE-GmbH/magento-2#247]
The AddressCheck is always executed for Ajax-Calls or WebApi-Requests. 
Also when the AddressCheck is NOT enabled in the backend. 
This slows down the Checkout/Requests depending on how many quotes you have in your system.

**See here:**
https://github.com/PAYONE-GmbH/magento-2/blob/342801016a66a199c52bb7e97f9beb30d728b496/Model/Plugins/ShippingAddressManagement.php#L84

**And here:**
https://github.com/PAYONE-GmbH/magento-2/blob/342801016a66a199c52bb7e97f9beb30d728b496/Model/Plugins/BillingAddressManagement.php#L77

The code should check if address check is activated.
Should I provide a PR?

Greetings

**Comment by T-Kuchel** [comment]
Hello @bjoern-flagbit ,

thank you for this helpful hint.
We will check that issue and come back to you with the results.

Greeting from Kiel

**Comment by T-Kuchel** [comment]
Hello @bjoern-flagbit ,

right before the request will be executed, there is a check if the execution is enabled:
https://github.com/PAYONE-GmbH/magento-2/blob/master/Model/Api/Request/Addresscheck.php#L155

It is possible that this is very late and many lines of codes are processed. Maybe we should/could think about it to makes this a little bit earlier.

What is your advice or how would you solve that?

Greetings from Kiel

**Comment by bjoern-flagbit** [comment]
This is nice to know, I did not found it 👍 Thx

But still the main problem is when you have to many quotes it will always do collection calls ... and this slows down ... because the code try to copy the old value from addressCheck ... So my advice is to do nothing with the quotes when the AddressCheck is disabled.
