### ISSUE TITLE
Incompatibility with Magento 2.3.2

### ISSUE THREAD

**Issue by bheindl** [PAYONE-GmbH/magento-2#248]
The current workaround to pass CSRF validation in Payone\Core\Controller\Transactionstatus\Index line 118 - 123 does not work anymore.

CSRF validation has changed in Magento 2.3.2: Request Param "ajax" is set to true inPayone\Core\Controller\Transactionstatus\Index. But Magento\Framework\App\Request\CsrfValidator does not check for this param anymore, but for $request->isXmlHttpRequest() (line 75). Therefor all callbacks to transaction status do not work anymore.

**Comment by T-Kuchel** [comment]
Hello @bheindl ,

thank you for this useful hint. We check this and come back to you with further informations or in best case with a fix of that.

Greetings
