### ISSUE TITLE
Wenn ich als Kunde eine Paypal Bestellung abbreche, wird der Warenkorb gelehrt.

### ISSUE THREAD

**Issue by espressobytes** [PAYONE-GmbH/magento-2#25]
**Schritte zur Reproduktion:**

1. Einen Artikel in den Warenkorb legen und zur Kasse gehen.
2. Bei der Kasse Zahlungsart PayPal auswählen.
3. Warten bis die Seite von PayPal fertig geladen hat und anschließend auf zurück gehen.

**Aktuelles Verhalten:**

Man kommt wieder auf die Shop-Seite, allerdings mit der Meldung der Warenkorb ist leer.

**Erwartetes Verhalten:**

Der Warenkorb enthält die Artikel, die ich zuvor hineingelegt habe.

**Comment by fjbender** [comment]
@espressobytes Das kann ich leider nicht reproduzieren. Um welche Magento- und Plugin-Version geht es genau?

**Comment by espressobytes** [comment]
Magento Version 2.1.0
Plugin-Version 1.3.1. (also das letzte Release)

Es wird eine Bestellung angelegt, sobald der User auf "Jetzt zahlen" klickt. Diese Bestellung bleibt vorerst im Status "pending". 
Wenn man dann auf "zurück" geht, wird die Warenkorb-Seite aufgerufen (Der Warenkorb ist aber, wie schon gesagt, leer).
Das Verhalten ist reproduzierbar, tritt aber nicht auf, wenn man den Paypal-Express Button verwendet.

**Comment by fjbender** [comment]
Ich habe folgendes Setup nachgestellt:

```
florian@charon:/var/www/html/shops/magento2/210fb$ php bin/magento --version
Magento CLI version 2.1.0
florian@charon:/var/www/html/shops/magento2/210fb$ composer show payone-gmbh/magento-2
name     : payone-gmbh/magento-2
descrip. : PAYONE payment gateway for all German online and offline payment methods including PayPal, all major Credit Cards and Maestro.
keywords : 
versions : * v1.3.1
type     : magento2-module
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
license  : Academic Free License v3.0 (AFL-3.0) (OSI approved) https://spdx.org/licenses/AFL-3.0.html#licenseText
source   : [git] https://github.com/PAYONE-GmbH/magento-2.git f7143bbdfeb867ba322a86c3d6a3f998692985c1
dist     : [zip] https://api.github.com/repos/PAYONE-GmbH/magento-2/zipball/f7143bbdfeb867ba322a86c3d6a3f998692985c1 f7143bbdfeb867ba322a86c3d6a3f998692985c1
names    : payone-gmbh/magento-2
[...]
```

Auch dort konnte ich das Verhalten nicht reproduzieren. Bitte kontaktieren Sie unseren Technical Support unter 0431/25968-500 oder tech.support@payone.de unter Angabe Ihrer Merchant ID und mit Verweis auf diesen Thread. Möglicherweise liegt hier ein anderes Problem vor (z.B. `backurl` Parameter).

**Comment by espressobytes** [comment]
Hallo,

Leider trat das Verhalten auch auf, nachdem ich zum Testen alle anderen selbstentwickelten Module deaktiviert habe.
Nochmal, damit es ganz klar ist: Es geht nicht um den "Zurück-Link" in Paypal sondern darum, wenn man im Browser auf den "Zurück-Pfeil" klickt.

Ich habe aber schon die Ursache gefunden. Vielleicht könnt ihr das überprüfen und ggf. anmerken, sollte die die Möglichkeit bestehen, dass dies andere ungewünschte Seiteneffekte haben könnte.

**Ursache:**

In Klasse: `Magento/Quote/Model/QuoteManagement`
Methode: `protected function submitQuote(QuoteEntity $quote, $orderData = [])`
...wird (in Zeile 487) das `$quote`-Objekt auf Inactive gesetzt:

`$quote->setIsActive(false);`

Das hat zur Folge, dass nach diesem Aufruf jegliche Artikel aus dem Warenkorb fallen, sollte der User wieder auf irgendeine Shopseite kommen. 

**Lösung**

Observer für den Event `sales_model_service_quote_submit_success`:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="sales_model_service_quote_submit_success">
        <observer name="paypal_quote_submit" instance="MyNamespace\PayoneFix\Observer\PaypalQuoteSubmit" />
    </event>
</config>
```

Observer Class:

```
<?php

namespace MyNamespace\PayoneFix\Observer;

use Magento\Framework\Event\ObserverInterface;

class PaypalQuoteSubmit implements ObserverInterface
{
    /**
     * @param \Magento\Framework\Event\Observer $observer
     * @return $this
     */
    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        /** @var \Magento\Sales\Model\Order $order */
        $order = $observer->getEvent()->getOrder();
        if ($order->getPayment()->getMethod() == "payone_paypal") {
            $quote = $observer->getEvent()->getQuote();
            $quote->setIsActive(true);
        }
        return $this;
    }
}
```

Wie gesagt, es wäre super, wenn ihr das mal nachprüfen könntet.

**Comment by fjbender** [comment]
> Es geht nicht um den "Zurück-Link" in Paypal sondern darum, wenn man im Browser auf den "Zurück-Pfeil" klickt.

Das war die kritische fehlende Information ;) Jetzt kann ich das Verhalten auch reproduzieren. Wir schauen uns das mal an. Danke für den Lösungsvorschlag!

**Comment by espressobytes** [comment]
Hallo,

Hab meinen letzten gelöscht, weil ich noch einen Fehler im Lösungsvorschlag gesehen habe.
Genau, es geht nicht um den "Zurück-Link" in Paypal sondern darum, wenn man im Browser auf den "Zurück-Pfeil" klickt.

**Ursache:**

In Klasse: `Magento/Quote/Model/QuoteManagement`
Methode: `protected function submitQuote(QuoteEntity $quote, $orderData = [])`
...wird (in Zeile 487) das `$quote`-Objekt auf Inactive gesetzt:

`$quote->setIsActive(false);`

Das hat zur Folge, dass nach diesem Aufruf jegliche Artikel aus dem Warenkorb fallen, sollte der User wieder auf irgendeine Shopseite kommen. 

**Lösung**

Observer für den Event `sales_model_service_quote_submit_success`:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="sales_model_service_quote_submit_success">
        <observer name="paypal_quote_submit" instance="MyNamespace\PayoneFix\Observer\PaypalQuoteSubmit" />
    </event>
</config>
```

Observer Class:

```
<?php

namespace MyNamespace\PayoneFix\Observer;

use Magento\Framework\Event\ObserverInterface;

class PaypalQuoteSubmit implements ObserverInterface
{
    /**
     * @param \Magento\Framework\Event\Observer $observer
     * @return $this
     */
    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        /** @var \Magento\Sales\Model\Order $order */
        $order = $observer->getEvent()->getOrder();
        if ($order->getPayment()->getMethod() == "payone_paypal") {
            /** @var \Magento\Quote\Model\Quote $quote */
            $quote = $observer->getEvent()->getQuote();
            $quote->setIsActive(true);
            $quote->setReservedOrderId(null);
        }
        return $this;
    }
}
```

` $quote->setReservedOrderId(null);` ist für folgenden Fall wichtig: Der Kunde wird auf die Paypal-Seite gelenkt, dann bricht er die Zahlung ab.
Dann geht er aber wieder auf die Paypal-Seite oder wählt eine andere Bezahlmethode.
Falls `$quote->setReservedOrderId(null);` nicht im Observer steht, gibt's einen SQL-Fehler, weil nicht zweimal dieselbe Increment-ID vergeben werden kann.

Wie gesagt, es wäre super, wenn ihr das mal nachprüfen könntet.

**Comment by smiler51** [comment]
Wir haben das gleiche Problem, aber es ist wesentlich schlimmer. Es tritt auch bei Sofort-Überweisung und wahrscheinlich den anderen Zahlungsmethoden auf. 

Man bestellt, geht auf die Payment Seite, kommt mit dem Backbutton des Browsers zurück und der Warenkorb ist leer. 

Die Bestellung wird aber als bezahlt in Magento verbucht und der Kunde bekommt eine Bestellbestätigung zugeschickt. Er hat aber nie etwas gezahlt.

Wir sind auf Magento 2.1.3 und auf der letzten Release des Plugins. Haben es gestern nochmal installiert.

Danke!

**Comment by fjbender** [comment]
@smiler51 Die Bestellung sollte nicht als "Bezahlt" verbucht werden. Hierfür haben wir im Modul das Transaktionsstatus-Mapping, welches sicherstellt, dass Bestellungen nur als "Bezahlt" markiert werden, wenn die Transaktion auch bei Sofort durchgeführt wurde.

Die Bestellung sollte zwar angelegt werden, allerdings im Standard Magento Order Status verharren, bis ein Update durch unsere Plattform erfolgt. Dann sollte der entsprechende Wechsel des Status getriggert werden. Bestellungen, für die kein Transaktionsstatus eingeht wurden auch nicht ordnungsgemäß abgeschlossen.
