### ISSUE TITLE
Orders with virtual products get wrong status "Closed"

### ISSUE THREAD

**Issue by alexandergolz** [PAYONE-GmbH/magento-2#253]
Orders in our magento 2.3.2 shop with virtual products like downloads get the status "Closed" instead of "Complete" after the transaction status "paid" is submitted from Payone. After reading the magento docs I think this is the wrong status. Also the button for credit memo (Gutschrift) is missing in admin in these orders and corresponding invoices. This seems to be even the main reason for this: I hunted down the code responsible for this in vendor/magento/module-sales/Model/ResourceModel/Order/Handler/State.php:

if (in_array($currentState, [Order::STATE_PROCESSING, Order::STATE_COMPLETE])
		&& !$order->canCreditmemo()
		&& !$order->canShip()
) {
		$order->setState(Order::STATE_CLOSED)
				->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_CLOSED));

So why would these orders have canCreditmemo() == false? Orders which get shipped are not affected by this. Also orders which use Paypal Express get the correct status "Complete".

**Comment by webpeaks63** [comment]
I can confirm this issue too. Did you find a fix for this?

**Comment by alexandergolz** [comment]
Sadly, no. Maybe I try to contact the support later this week.

**Comment by hreinberger** [comment]
Hi all,
I can confirm this too, though the log details in the order are correct:
![grafik](https://user-images.githubusercontent.com/40197225/63687245-57349900-c804-11e9-9eb4-17cf95dd6bd8.png)
We'll check that out!

**Comment by webpeaks63** [comment]
After contacting payone support today, they confirmed the issue and forwarded it to their extension developer.
