### ISSUE TITLE
release for compatibility with Magento 2.3.2

### ISSUE THREAD

**Issue by berwa** [PAYONE-GmbH/magento-2#254]
The latest available release (2.6.0) is not compatible with Magento 2.3.2 as it lacks the changes from https://github.com/PAYONE-GmbH/magento-2/issues/248 that were added to the master branch after the release.
Are there already plans to provide a new release that includes these changes?

Thank you and Best regards

**Comment by fjbender** [comment]
We have loose plans for a release. However, there are still some changes pending that we would like to include (for instance Amazon Pay SCA for PSD 2 readiness).

I'll check whether we could provide some kind of smaller release to ensure Mage 2.3.2 compatibility.

**Comment by mukki182** [comment]
Hello Mr Bender,
do you have a temporary workaround for this issue?
Can i use the master branch for production system?
Best Regards

**Comment by fjbender** [comment]
You can try to backport the patch from #252 that fixes this issue. Using the master in production is possible, but discouraged as it is not thoroughly tested (PRs get tested individually before merge, a full test is only conducted before a release).

**Comment by juules** [comment]
Hello,
we're still waiting for a release that includes these changes ... any updates on this topic?
Best regards

**Comment by hreinberger** [comment]
Sadly, not yet. As @fjbender stated above we'd like to include the required changes for PSD2 directly into the next release.

**Comment by davidverholen** [comment]
@fjbender do you have (a rough) estimate when the psd2 work will be finished? Of course it's important but depending on how long it takes 2.3.2 compatibility becomes more important, too ;)

**Comment by fjbender** [comment]
We see the issue of a missing release as a pressing matter, both because of 2.3.2 and PSD2. We're still waiting on the latest changes for PSD2 compat and will then release asap.

**Comment by berwa** [comment]
Hello @fjbender,
as two more weeks have passed now: are there any news about this topic or a planned date for the release?

Best regards

**Comment by fjbender** [comment]
Sorry for the delay, this is taking much longer than expected. We'll try to squeeze it in this week, but have another release scheduled as well, so it might take until the next.

**Comment by hreinberger** [comment]
Hi all,
we just published our update to v2.7.0, which fixes this! Thanks for your patience!
