### ISSUE TITLE
Url call on /payone/transactionstatus returns 302 instead of 200

### ISSUE THREAD

**Issue by Detzler** [PAYONE-GmbH/magento-2#255]
After upgrading to Magento 2.3.2 and Payone 2.6.0 on every call from payone to magento (/payone/transactionstatus) the server returns code 302 instead of 200. This should explain why no payment confirmation is created in our magento instance.
No log entries available. 
Manual ur call in browser on /payone/transactionstatus returns 200 with message: "Access denied". So the module (controller) is available.
Can't provide more info currently. Can anyone confirm compatibility with Magento 2.3.2 and Payone 2.6.0?

**Comment by fjbender** [comment]
We have issues with the CSRF validation in Mage 2.3.2, #252 has fixed this, but is not yet included in a release. Can you try Mage 2.3.2 with dev-master?

**Comment by Detzler** [comment]
It works thx.

**Comment by Flyingmana** [comment]
please do a release which contains this fix
