### ISSUE TITLE
Fehlermeldung nur auf englisch

### ISSUE THREAD

**Issue by espressobytes** [PAYONE-GmbH/magento-2#26]
Wenn man im letzten Checkout-Schritt falsche Kreditkarten-Daten angibt, erscheint eine Fehlermeldung vom Payone-Server, z.B.:

Invalid card number. Please verify your card data.

Der Text kommt aus dem javascript des iFrames.

Gibt es die Möglichkeit, dass diese in deutscher Sprache erscheint? 
Oder ist dies ein Bug?

**Comment by fjbender** [comment]
Ist konfigurierbar: Magento Backend -> Payone -> General -> Payment Creditcard -> Custom Styling -> Error Output (muss aktiviert sein und als Sprache "Deutsch" ausgewählt)
