### ISSUE TITLE
psd/2 compliance release

### ISSUE THREAD

**Issue by davidverholen** [PAYONE-GmbH/magento-2#260]
@fjbender just creating it for tracking updates on this topic.
Do you have a rough timeline for the release? Since we also need to start planning the updates and testing for all involved projects

**Comment by hreinberger** [comment]
Hi @davidverholen we're aiming for a release next week. Would have loved to deploy this week but we still have some work to do on Amazon Pay. 

By the way if you don't use Amazon Pay, you can configure the plugin for 3D Secure 2.0 right now: https://docs.payone.com/display/public/INT/Magento+2+Plugin#Magento2Plugin-EnsuringMaximumConversionWith3DSecure2.0

**Comment by andreasberenz** [comment]
Just a little push here. Are there any news?

**Comment by fjbender** [comment]
See #254 and my comment there. We try to have a release this week, the next the latest. Everything was taking way longer than expected.

**Comment by hreinberger** [comment]
Hi all,
we just published our update to v2.7.0, which fixes this! Thanks for your patience!
