### ISSUE TITLE
PHP 7.3 compatibility

### ISSUE THREAD

**Issue by domeglic** [PAYONE-GmbH/magento-2#267]
Supported php versions do not include 7.3.  `"php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0"`

Magento 2.3.3 now [supports](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php) php 7.3.

**Comment by fjbender** [comment]
Thanks for pointing this out. Created a PR, testing should be quick.
