### ISSUE TITLE
composer require with php7.3

### ISSUE THREAD

**Issue by NilsHansen** [PAYONE-GmbH/magento-2#269]
Hi,
in the closed issues it says that payone-magento2 now supports php7.3...  
In my fresh magento2 install I used this command:  
`composer require payone-gmbh/magento-2`  
This gives me composer back:  
`Package payone-gmbh/magento-2 at version  has a PHP requirement incompatible with your PHP version (7.3.12)`

If I force composer by using the parameter `--ignore-platform-reqs` it is getting installed. Sadly I have to include that parameter now on every other extension I am installing via composer...
Also in the composer.json that has been downloaded to my vendor/payone-gmbh folder PHP 7.3 is not added to the php/require section... 
Maybe my composer gets some old sources?
How can I download the current version? 
I have already cleared the composer cache by typing: `composer clearcache`

**Comment by fjbender** [comment]
Hi,

This is due to the fact that we haven't released a new version yet, see https://github.com/PAYONE-GmbH/magento-2/compare/v2.7.0...master

Once we have a version newer than v2.7.0, you should be fine again. In the meantime, you could work around that by installing the master branch `composer require payone-gmbh/magento-2 dev-master`, however, this might not be a smart idea for production deployments, as the master branch is usually lacking end-to-end testing.

**Comment by NilsHansen** [comment]
Hi,

hm, okay... At production this should be no problem, as there is php7.2... This is just for our dev environment...

Thanks alot!

**Comment by ridesoft** [comment]
Hi, is possible to know which incompatibilities with version 7.3 there are?

We are in a really bad situation right now: we have in production php 7.3 and of course we don't want to install our extensions with `--ignore-platform-reqs` but on the other hand install the dev-mater version is not a good solution as well.

A temporary option could be to download the zip and install the module directly under *app/code* and then, when you release the new version, we can use composer again.

There are critical issues with php 7.3?

**Comment by fjbender** [comment]
There are currently no known incompatibilities with PHP 7.3.

We'll see that we squeeze in a new release some time soon, but we currently have a big pipeline of release tests :/
