### ISSUE TITLE
mode wrong on refund

### ISSUE THREAD

**Issue by phoenix-bjoern** [PAYONE-GmbH/magento-2#271]
When creating a refund from an invoice in the Magento backend the TX mode is set to "test" although the order has been placed in "live" mode. It seems the module retrieves the configuration from a wrong scope instead from the order which is currently processed.

**Comment by fjbender** [comment]
In theory we should grab the mode from the order:

https://github.com/PAYONE-GmbH/magento-2/blob/11dea078744b5337393fe17289043d5b1e5356ba/Model/Api/Request/Debit.php#L143-L160

I can't spot anything wrong here - or maybe I am missing something?

**Comment by phoenix-bjoern** [comment]
But `$oPayment->getOperationMode()` doesn't have any input parameter. And since you don't use store emulation in the function `setStoreCode()` this method doesn't know about the current store:

```    
public function getOperationMode()
{
        return $this->getCustomConfigParam('mode');
}

**Comment by fjbender** [comment]
Ah, makes sense. We will get it fixed.

**Comment by fjbender** [comment]
Can you confirm that #273 fixes this issue?
