### ISSUE TITLE
Order Confirmation email not sent

### ISSUE THREAD

**Issue by omargits** [PAYONE-GmbH/magento-2#274]
Order emails not transmitted. I am using Magento 2.3.3 Payone module version 2.7.0
from
Protocol - TransactionStatus
its appointed and then paid but still upto now no email. Magento cron is working fine.
on Server varnish 5.01. from above you said return url must be
website.com/payone/transactionstatus
returns Access denied
please guide us what to do

**Comment by hreinberger** [comment]
Like my last comment in #193 - I'd like to ask you to contact our support team so the people there can first analyze your individual configuration and afterwards file a ticket with us internally. This seems mostly like a config issue for me.

**Comment by omargits** [comment]
Support check the settings and found ok but for emails issue they said cant guide about it. by the way if we choose other payment method credit card then emails are working any idea for debugging and checking where exactly the issue is

**Comment by omargits** [comment]
any update ? @hreinberger  @gerritpechmann @fjbender With payone - paypal order email not triggers and for credit card 3d validation not working plz guide
