### ISSUE TITLE
$_SERVER["REMOTE_ADDR"] vs $_SERVER["HTTP_X_REAL_IP"]

### ISSUE THREAD

**Issue by jcglindemann** [PAYONE-GmbH/magento-2#275]
If you are in a cloud environment or use the varnish cache the 
$_SERVER["REMOTE_ADDR"] will show mostly the local IP (127.0.0.1) and the $_SERVER["HTTP_X_REAL_IP"] will give the "real remote IP".
In this case the API from payone try to access https://www.domain.com/payone/transactionstatus
to give back the status, but this will fail because 127.0.0.1 is not in th list of allowed IPs.

So I suggest to 
1. check if the remote IP is in the list of allowed IPs
2. check if the remote IP is 127.0.0.1 - if yes check the $_SERVER["HTTP_X_REAL_IP"]

maybe better will be have a configuration setting in the backend for this "additional check $_SERVER["REMOTE_ADDR"]"

**Comment by fjbender** [comment]
Sorry for getting back to you so late. I feel like this should already be handled with the "Proxy Mode" configuration option in `\Payone\Core\Helper\Environment::getRemoteIp`
