### ISSUE TITLE
Issue with generating the order invoice

### ISSUE THREAD

**Issue by hardiklinksture** [PAYONE-GmbH/magento-2#277]
We are using the Payone payment method extension with our existing Magento 1 live site and we have configured below payment method on our existing M1 website.

- POSTFINANCE CARD
- POSTFINANCE E-FINANCE
- PAYPAL
- KREDITKARTE

So, when we/customer will place the order on the existing M1 website then the order invoice is generated via CRON `payone_core_cronjob_transactionstatus_process`

Now we have migrated the Magento 1 to Magento 2 and we are using this Payone Payment method extension `https://github.com/PAYONE-GmbH/magento-2`

Also, we have configured above all payment methods on our staging site which is migrated from M1 to M2.

Now, while we place an order via PAYPAL and KREDITKARTE using Test mode then the order will be placed successfully but the order `Invoice` will not generate on the staging site which is migrated from M1 to M2.

Just for your information, we are using Magento version 2.3.3.

So, can you please let us know your thought for the same?

**Comment by fjbender** [comment]
For the invoice to be automatically generated, two things have to be given:
1. Mode must be set to authorization (preauthorization requires manual generation of the invoice)
2. The transaction status `appointed` must be received

Can you confirm that both are given for your staging environment? Especially when migrating, it might be neccessary to have a second payment portal on the Payone platform to be able to use a second Transaction Status URL.

**Comment by hardiklinksture** [comment]
Yes, we have configured the Payone Payment method on the staging environment with test mode.

Please check the below three screenshot for more information and let us know your thoughts on that.

![3](https://user-images.githubusercontent.com/24790922/71721528-6d560400-2e4b-11ea-8998-b72e1fd8d1f0.png)

-----------------------------------------

![2](https://user-images.githubusercontent.com/24790922/71721548-7fd03d80-2e4b-11ea-9f69-791caa01a91c.png)

----------------------------------------

![1](https://user-images.githubusercontent.com/24790922/71721557-865eb500-2e4b-11ea-9930-f33ad51191c8.png)

**Comment by fjbender** [comment]
Okay, I looked at the logs for this transaction.

You try to deliver the Transaction Status notification to the old URL of the Magento 1 shop. If you need assistance on how to change this (and about the possible risk for the currently running shop), please contact our technical support team, as this is not an issue with the Magento 2 plugin itself.

Thanks
Florian
