### ISSUE TITLE
window[c] is not a function error when switching to hosted iframe

### ISSUE THREAD

**Issue by danisowa** [PAYONE-GmbH/magento-2#278]
### Summary
If i use ajax script everything is working
<script src="https://secure.pay1.de/client-api/js/ajax.js"></script>
var request = new PayoneRequest(po_data, po_options);

When i change ajax script to hosted iframe script and change the call like it is described in documentation to:
<script type="text/javascript" src="https://secure.pay1.de/client-api/js/v1/payone_hosted_min.js"></script>
var request = new Payone.ClientApi.Request(po_data, po_options);  

i get an error 
**window[c] is not a function** 
and it is not possible to execute the paypal payment.
Any Ideas what could be the reason for this?

edit: just recognized that i have posted in magento-2 tree, this is not a magento-2 problem this is a general problem, but maybe someone has an idea

**Comment by fjbender** [comment]
Hi,

which documentation are you referring to? Sounds like you're trying to implement the API on your own, and not use the Magento 2 module? This repository is for Magento 2 module issues only. If you're trying to implement the API, please contact the Technical Support Team.

Thanks
Florian
