### ISSUE TITLE
Incorrect encoding in Model/Methods/OnlineBankTransfer/Eps.php

### ISSUE THREAD

**Issue by schmengler** [PAYONE-GmbH/magento-2#280]
This file is encoded in ISO-8859-1 and contains bytes that are not valid in UTF-8, e.g. in `Ärztebank`.

Instead of using `utf8_encode($sTitle)`, the file itself should be UTF-8 encoded.

In Magento 2.3.4, the incorrect encoding leads to the issue that integration tests cannot be executed anymore, when PHPUnit saves the state of all static properties but cannot serialize `static $aBankGroups`

**Comment by fjbender** [comment]
Should be an easy fix.

**Comment by fjbender** [comment]
Can you try running the integration tests again with the current `master` branch? :)

**Comment by schmengler** [comment]
@fjbender Can confirm, it works on the master branch. Thank you!
