### ISSUE TITLE
Payolution_Installment uses deprecated prototypeJS dependency

### ISSUE THREAD

**Issue by jlewko** [PAYONE-GmbH/magento-2#283]
Payolution_Installment uses deprecated **prototypeJS** dependency in it JS method-renderer file:
`magento-2/view/frontend/web/js/view/payment/method-renderer/payolution_installment-method.js`
This creates an issue while trying to select a different address from the list of available addresses in checkout's **Review & Payment** step. 
With returned street address data it prints also a part of the **legacy-build.min.js** file.
Screenshots:
1. Selecting a different address:
<img width="418" alt="checkout-payment-method-address-change" src="https://user-images.githubusercontent.com/6950535/72553568-51198480-3899-11ea-969e-ab24c950a0a0.png">
2. Described issue after address update has been made:
<img width="425" alt="checkout-payment-method-address-change-afterUpdate" src="https://user-images.githubusercontent.com/6950535/72553651-760df780-3899-11ea-81f6-b50c8a12f2a8.png">

I've prepared a PR in order to fix this issue: #284

**Comment by fjbender** [comment]
Thanks for the well-documented issue and PR :) We'll take a look and test it. Does this affect all Magento versions?

**Comment by jlewko** [comment]
It was tested on v2.3.2 but I guess it starts with Magento change regarding  concatenation of possible multiple street addresses data from this PR:
https://github.com/magento/magento2/commit/98e8ea7cd181e6e68fc5d1c7c67f723e6dedc159

**Comment by fjbender** [comment]
All right, thanks! We'll then also check if this breaks 2.2 compatibility.
