### ISSUE TITLE
translate issue

### ISSUE THREAD

**Issue by hardiklinksture** [PAYONE-GmbH/magento-2#288]
Place an order via Creditcard and my store language is "De".

But on order email payment Text steel in English.
Check the below screenshot for the same.

![download](https://user-images.githubusercontent.com/24790922/74406805-9c9e5e80-4e56-11ea-8b67-a46714d2c8c8.png)

**Comment by fjbender** [comment]
I suppose your block in the email template looks something like this:

```
                    <td class="method-info">
                        <h3>{{trans "Payment Method"}}</h3>
                        {{var payment_html|raw}}
                    </td>
```

In the `payment_html` variable the stuff from \Payone\Core\Block\Info\Creditcard::_prepareSpecificInformation gets inserted. The strings there are in a `__` wrapper, so should be translated. However, due to Magento, in this context the locale of the Default Store seems to be used.

You could either use another language for the Default Store or find a way to wrap the `var` output through `trans` (I am not sure how that would work, as I basically don't know anything about email templating).

**Comment by hardiklinksture** [comment]
Yes my email template is the same as you provide like 

`{{var payment_html|raw}}`

I check below file for the title it is ok as you describe The strings there are in a` __` wrapper, 


/Payone/Core/Block/Info/Creditcard.php

![Screenshot from 2020-02-13 16-41-28](https://user-images.githubusercontent.com/24790922/74428832-c4ee8300-4e7f-11ea-9c95-bbfe4c487937.png)

Also, we have only one store which is **de_DE** But steel not working.

Thanks

**Comment by fjbender** [comment]
Thanks for the feedback! In general, this seems more like a Magento issue to me. I'll try and find something out about this, but can't guarantee any success here. 

If you find a solution by asking your Magento Expert of Least Distrust™ or the community, sharing it here would be greatly appreciated!

**Comment by drabikowy** [comment]
I might have more info on this. Our client reported this issue to us. And I've tried to reproduce it first. Basically - I've received a properly translated email which was sent automatically when I placed an order. Then I resend the one form the admin panel - not translated.

**Comment by adamkarnowka** [comment]
When sending e-mail from admin panel, locale context is taken from currently logged admin's locale, so quick win fix would be to use desired locale.
I have worked around this issue by patching `vendor/payone-gmbh/magento-2/Block/Info/Basic.php` and adding environment emulation class:

`$this->emulation->startEnvironmentEmulation($oOrder->getStoreId(), 'frontend');`

This way, while sending e-mail template and translations for e-mail are taken from store where order has been placed at. It also must be done for all methods that have specific payment details (CC, Debit, SafeInvoice, etc.) - therefore I don't create pull request - it would be better to have this somewhere "above".

Kind regards,
Adam
