### ISSUE TITLE
Long ReferenceNumber Prefix results in 1003: Reference Number faulty or missing

### ISSUE THREAD

**Issue by riconeitzel** [PAYONE-GmbH/magento-2#293]
If the referencenumber prefix (admin > stores > config > payone > general > global > referencenumber prefix) exceeds (a not yet defined number of) characters, the checkout process returns an error `1003: An error occurred while processing this transaction (wrong parameters)`

Test: set referencenumber prefix to "abcdefghijklmnopqrstuvwxyz" and try to checkout.

Possible fix: define and document the allowed number of characters for this field. validate the entered string to not exceed the defined character limit

@fjbender if you figure the number I might be able to create a PR :-)

**Comment by fjbender** [comment]
The maximum length for reference is 20 (16 for Giropay)(https://docs.payone.com/display/public/PLATFORM/reference+-+definition). The maximum length of the prefix thus depends on the length of the Magento order number. Limiting it to 5 might be a good idea.

Any oppinion @T-Kuchel @hreinberger ?

**Comment by riconeitzel** [comment]
It might help to add a clarifying comment "the max. length of the payment reference is 20 characters. depending on you order number pattern the length of you prefix varies between 0-10"

**Comment by fjbender** [comment]
Seems like the easiest way. Should be in the Docs as well.

**Comment by hreinberger** [comment]
I updated our docs with a warning: https://docs.payone.com/display/INT/Magento+2+Plugin#Magento2Plugin-Global
