### ISSUE TITLE
magento 2.1 version constraints 

### ISSUE THREAD

**Issue by davidverholen** [PAYONE-GmbH/magento-2#3]
I just tried to install the dev-master version. There is a problem with installing it on magento 2.1.2.

Magento 2.1 requires magento/module-framework 100.1.2 and the payone module requires 100.0.*
Same problem for the magento/module-store extension.

To make it installable with magento 2.1 via composer (if 2.1 is supported) you have to change the constraints in the composer.json

for example:

```json
{
    "name": "payone-gmbh/magento-2",
    "description": "PAYONE FinanceGate payment gateway for all german online and offline payment methods including PayPal, all major Credit Cards and Maestro.",
    "type": "magento2-module",
    "version": "1.2.2",
    "license": [
      "OSL-3.0",
      "AFL-3.0"
    ],
    "require": {
        "php": "~5.5.0|~5.6.0|~7.0.0",
        "magento/framework": "^100.0.0",
        "magento/module-store": "^100.0.0"
    },
    "autoload": {
        "files": [
            "registration.php"
        ],
        "psr-4": {
            "Payone\\Core\\": ""
        }
    }
}
```

the ^ constraint operator allows increasing the minor and bugfix version but not the major version

**Comment by fjbender** [comment]
Added the ^ operator. Will tag next release as soon as we have something substancial to add... ;)
