### ISSUE TITLE
License

### ISSUE THREAD

**Issue by theCapypara** [PAYONE-GmbH/magento-2#319]
Hi,

it is unclear what the software license for this module is.
1. The repository does not contain a license file
2. The link in the README.md doesn't work
3. The composer.json states that the license is OSL 3.0 / AFL 3.0
4. The copyright headers of the files say the license is LGPLv3

Could you please clarify what the license for the module is?

**Comment by fjbender** [comment]
Thanks for reaching out. We're currently somewhat "unharmonic" with our license zoo. We do have a strong preference towards MIT; however, have not yet migrated all projects towards it.

Currently, this project is licensed under LGPLv3, OSL 3.0, or AFL 3.0 at your option, as there is no clear statement available.
