### ISSUE TITLE
Always magento status show pending instead of processing.

### ISSUE THREAD

**Issue by nilarocks** [PAYONE-GmbH/magento-2#323]
I have update my magento version 2.1.9 to 2.3.3.
After update we have some issue, all order status are set Pending instead of processing. Payment also successfully add.
After some debug i got, below url give 302 status code
 
https://siteurl/payone/onepage/redirect/

I also check in both. Live and test mode. both has same issue.

**Comment by fjbender** [comment]
This should have been fixed with #216 

Which version of the module are you running?

**Comment by nilarocks** [comment]
module version is 2.8.1

**Comment by fjbender** [comment]
Okay, then it seems like this is a individual issue that needs more analysis. Please contact our technical support team at tech.support@payone.com

Thanks
