### ISSUE TITLE
How to remove PAYONE - Klarna method?

### ISSUE THREAD

**Issue by nilarocks** [PAYONE-GmbH/magento-2#324]
I have checked in backend Store->Configuration->Payone->Payment, there is no any option to remove completely from payment section .

can you please tell how can we remove it?

**Comment by fjbender** [comment]
Hi @nilarocks 

which version of the plugin are you using? This is important for us because we have recently made changes to Klarna

**Comment by nilarocks** [comment]
Latest 3.0.0
I have download from here 
https://github.com/PAYONE-GmbH/magento-2/releases

**Comment by fjbender** [comment]
Thanks

I could validate this as a bug. We will issue a fix asap.

**Comment by fjbender** [comment]
We have a proposed fix with #325 which has been moved to QA now.
