### ISSUE TITLE
Amazon Pay as selectable payment-method in checkout

### ISSUE THREAD

**Issue by berwa** [PAYONE-GmbH/magento-2#329]
Hello Payone-team,
on of our customers asked whether it is possible to add Amazon Pay to the list of available payment-methods in the Magento checkout (payment step), additionally to the already displayed buttons in the cart.

We already checked the documentation and could not get it working, so we are not really sure if that is a bug or not yet supported by the extension.

It seems like the Magento Core-integration does support this possibility: https://docs.magento.com/user-guide/images/images/config-sales-payment-methods-amazon-pay-advanced-frontend.png (taken from https://docs.magento.com/user-guide/payment/amazon-pay-setup.html)

*technical Information*
Magento Commerce 2.3.5-p1
Extension-Version: 2.8.0

Thank you in advance and best regards

**Comment by T-Kuchel** [comment]
Hi @berwa ,

right now this is not support by our extension. We only have implemented amazon pay as an express payment method, so that this method is not shown in the payment page, only in the cart or mini-cart.

Greetings from Kiel
Timo

**Comment by berwa** [comment]
Hello @T-Kuchel 
thank you for your reply.

Are there any plans to integrate this features into the module in the future?

Best regards

**Comment by T-Kuchel** [comment]
Hi @berwa ,

not for the moment, sorry.

Greeting from Kiel
Timo
