### ISSUE TITLE
Order cancellation using the browser's back button results in orders with twice the amount of items

### ISSUE THREAD

**Issue by therealtbs** [PAYONE-GmbH/magento-2#337]
Installed versions:
- Magento 2.3.3
- Payone-Extension 2.8.0

Steps to reproduce:
1. Add some products to cart
2. open the store in a second tab
3. in the first tab, checkout, select any payment method which causes a redirect (e.g. PayPal) and get redirected
4. in the second tab, open the checkout
5. in the first tab, finish the transaction with PayPal

Expected behavior:
- there are two completely identical orders created. One should be canceled and the other should be processing (or whatever is configured using the status-mapping)

Actual behavior:
- there are two orders created, however the second one (the "substitute-order" created by the Payone extension) has every item's quantity doubled

Potential causes:
https://github.com/PAYONE-GmbH/magento-2/blob/72f39a7e05f034e5717147dbf9b97ecb6ff6fe53/Model/Handler/Cancellation.php#L88-L96 

I don't know for certain whether this is a result of the extensions we have installed on our Magento store or if it can happen with any Magento 2.3.3 installation and we're just the first ones to notice this. But if the `$oCurrentQuote` is the same as is specified by the `$quoteId` it would get merged with itself. Whether or not this is a valid procedure is something I'll leave to the Magento devs to decide.

I think the fix is quite simple. Compare the IDs of the two quotes and only merge them if they are different.

**Comment by T-Kuchel** [comment]
Hi @therealtbs ,

if the fix is really quite simple for this complex flow we will check that and come back to you.

Greetings from Kiel
Timo

**Comment by fjbender** [comment]
Fixed with #340
