### ISSUE TITLE
Endless loading when the card type is incorrect

### ISSUE THREAD

**Issue by rafalbedlewicz** [PAYONE-GmbH/magento-2#339]
Steps to reproduce:

1. Go to checkout and select the credit card payment method;
2. Enter card number correctly but choose incorrect card type;
3. Fill out other required fields correctly and click the buy button.

Actual:

The error message is displayed, however, there is still loading overlay visible. The error in the console:

    payone_iframe_min.js?1598523914920:8 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Object.callback (https://secure.pay1.de/client-api/js/v1/payone_iframe_min.js?1598523914920:8:258)
    at https://secure.pay1.de/client-api/?request=creditcardcheck&responsetype=JSON&mode=test&mid=43578&aid=43789&portalid=2032268&encoding=UTF-8&storecarddata=yes&hash=a6f387410f34f8b7aabe22eaad292fe1&cardpan=4200000000000000&cardexpiremonth=2&cardexpireyear=2022&cardtype=M&channelDetail=payoneHosted&cardcvc2=432&callback_method=PayoneGlobals.callback:1:15`
Expected:

The loading finishes and the error message is displayed

**Comment by T-Kuchel** [comment]
Hi @rafalbedlewicz ,

which version of M2 are you using, and which version of the PAYONE integration?
I tried to reproduce it here, but your reported error/issue/behavior does not come up. 
I only get the expected error message and then I can enter/select new credit card parameters. No overlay is in the way.

Greetings from Kiel
Timo

**Comment by rafalbedlewicz** [comment]
Hi @T-Kuchel 

Magento ver. 2.3.2
and PAYONE integration version (I am not sure if I am checking it in the right way, please tell me if not):
`"`[`payone-gmbh/magento-2`](https://packagist.org/packages/payone-gmbh/magento-2)`": "`[`dev-master`](https://packagist.org/packages/payone-gmbh/magento-2)`"`

Greetings
Rafał

**Comment by T-Kuchel** [comment]
Hi @rafalbedlewicz ,

weird. No problems here on the same version. Have you tried do update with composer to get a 'better' result?
Wich version of the extension is used. Actual it is 3.1.0.

Greetings from Kiel
