### ISSUE TITLE
Migration Magento2 Mapping etc

### ISSUE THREAD

**Issue by michael-hxx** [PAYONE-GmbH/magento-2#34]
Hi
is there a plan for doing migration from magento1 (1.9.3.2) and latest payone extension to magento 2.1.4?
I need information for mapping etc
Thanks
michael

**Comment by fjbender** [comment]
Hi Michael,

I'm sorry, but we don't plan to support migration from Magento 1 to Magento 2. We tried, however, to keep things as consistent as possible.

Best
Florian
