### ISSUE TITLE
New behavior in Observer/TransactionStatus/Paid.php for advanced payment

### ISSUE THREAD

**Issue by andreasberenz** [PAYONE-GmbH/magento-2#348]
There is a new behavior in the mentioned file.

```
// if advance payment is paid should create an invoice
        if ($oOrder->getPayment()->getMethodInstance()->getCode() === PayoneConfig::METHOD_ADVANCE_PAYMENT) {
            $oInvoice = $this->invoiceService->prepareInvoice($oOrder);
            $oInvoice->setRequestedCaptureCase(Invoice::NOT_CAPTURE);
            $oInvoice->setTransactionId($oOrder->getPayment()->getLastTransId());
            $oInvoice->register();
            $oInvoice->save();

            $oOrder->save();

            if ($this->baseHelper->getConfigParam('send_invoice_email', 'emails')) {
                $this->invoiceSender->send($oInvoice);
            }
        }
```

Is there a traceable discussion why it is necessary to create an invoice instant after the TransactionStatus paid is received? In our case the former behaviour is preferred, that there is no invoice created. As I can see, the invoice is not captured, too. So in fact we ran into the problem, that we tried to refund an order, but it was not possible because the invoice was not captured. In Magento 2.4 the possibility to capture afterwards is missing, so we had a lot of trouble to clean up this case.

If there is no reason to keep this code, I would suggest to remove it or to make this behavior at least configurable.

**Comment by fjbender** [comment]
We do not have a traceable discussion, but I can explain why we did this.

There was an incompatibility with the Gift Card Accounts module from Magento Commerce, which resulted in Gift Card Accounts not being properly created when the Paid Status was received. The code change introduced in 174542c776d6ce82be6378cf20294dc50390aa9c fixed that.

I see multiple ways out of this:
1. We make this behavior entirely configurable
1. We somehow recognize that a Gift Card is in the order and only then execute this code
1. We find another clever way to solve the problem with the Gift Card module while retaining proper functionality

I will take this up with the authors of the patch and ask them to make a proposal here.

**Comment by andreasberenz** [comment]
I would prefer solution 1 or we find a clever way as proposed in 3.

We don't have cases with gift cards, so I can't understand the details here.

Regarding the accounting here, it is a hard decission here to be forced to create an invoice in dependency of this payment method when your invoicing strategy is to wait until the order is fulfilled.

**Comment by fjbender** [comment]
Hi @andreasberenz ,

with #359 we built a config-wrapper around this behavior. I'd like your opinion on that :)

Thanks
Florian

**Comment by andreasberenz** [comment]
Thanks a lot. Looks like a good solution for me!

**Comment by andreasberenz** [comment]
This is still not part of the official release, which is kind of annoying if you have to redeploy the vendor libraries.

**Comment by fjbender** [comment]
@hreinberger - I can't unassign me for some reason, but this looks like something you could fix :)

**Comment by hreinberger** [comment]
We have a new release in the works, but are a bit tight on QA resources right now, so I can't give an exact ETA.

**Comment by andreasberenz** [comment]
I understand the hesitation for releasing this. To introduce this change is another significant behavioral change. For me it would be fine to solve this, by enabling this option by default, so we can disable this setting after the update.
If this problem is exclusively ours, every other participant should be happy as well.
