### ISSUE TITLE
MAG2-96 doesn't fix existing config

### ISSUE THREAD

**Issue by riconeitzel** [PAYONE-GmbH/magento-2#367]
hi there,

if you have core_config_data entry with "store" instead of "stores" it's not fixed by MAG2-96. Instead the broken config stays in the DB and causes trouble later.

You should create a migration patch for it!

Rico

**Comment by fjbender** [comment]
Just to clarify: This only happens when you're coming from a version before #229 respectively MAG2-96 was applied, right?

**Comment by riconeitzel** [comment]
correct :-)

**Comment by fjbender** [comment]
Mhhh, I'm not convinced that introducing a migration for a change that happened almost two years ago is a smart choice. I'm afraid we'd open up more questions than actually improve things.

What "trouble" exactly is caused under which circumstances? I kinda wanna determine how big of an impact this issue has.

**Comment by riconeitzel** [comment]
our shops went down 😄

we deleted a website/store/store view … we looked for entries in core_config_data matching "stores" and the store view id. we removed everything.

Shops went down with "store not found" exception - incl. backend.

I figured out that there were entries for "store" and the store view id which we missed to delete.

SOME of them were already present with "stores" (they were saved after the fix I assume). some of them were solely under "store" scope. I removed duplicates and renamed the remainder. caused about 2hrs of production down time.

**Comment by fjbender** [comment]
All right, thanks for the detailed description. Then I indeed misjudged the impact of the issue. I'll move this to Dev.

**Comment by riconeitzel** [comment]
Any news here, before stalebot kills it?

**Comment by fjbender** [comment]
This issue is still in our backlog. We still are somewhat hesitant to touch this, in order to not break any more production shops.

**Comment by riconeitzel** [comment]
Silvester Stalelone … 😅
