### ISSUE TITLE
Not installable on 2.4.1

### ISSUE THREAD

**Issue by dmconnector** [PAYONE-GmbH/magento-2#370]
Hi, 
when trying to install via composer 
composer require payone-gmbh/magento-2
I get following error:
payone-gmbh/magento-2 v3.2.0 requires magento/framework ^100.0.0|^101.0.0|^102.0.0|^103.0.0 -> no matching package found.

**Comment by fjbender** [comment]
Hi @dmconnector,

I just tried it out in a freshly installed Magento 2.4.1 and haven't had any problems. Is your Magento set up completely?
