### ISSUE TITLE
Problem with id[n] parameter

### ISSUE THREAD

**Issue by a-litvin** [PAYONE-GmbH/magento-2#373]
Hi,

For order items with the custom options Magento joins a SKU of a product with an option name using ',' symbol between them. Then order item SKU is used in the transactional requests as an id[n] parameter. But using ',' in this parameter is forbidden: https://docs.payone.com/display/public/PLATFORM/id%5Bn%5D+-+definition.

Also id[n] parameter may be maxim 32 characters length, but in this case an order item SKU may be longer, that also may leads to error.

**Comment by fjbender** [comment]
Good catch, thanks!

We'd probably need to work around that, as it is unlikely that the specification of the id[n] parameter on the API will change.

Would it work to just omit the ',' and cut the string off after 32 chars? That's of course not the optimal solution, but should serve well as a workaround so transactions don't break.

**Comment by a-litvin** [comment]
> Would it work to just omit the ',' and cut the string off after 32 chars?

Thank you for reply!

Yes, this's working fine. But we're waiting this fix in the future release ;-)

**Comment by fjbender** [comment]
Will be fixed a future PR, will close this issue then
