### ISSUE TITLE
Wrong status

### ISSUE THREAD

**Issue by carlosblackdd** [PAYONE-GmbH/magento-2#381]
Hi, 

we have the problem, that this txid has the status: underpaid: 
![image](https://user-images.githubusercontent.com/5381639/115716940-03cc7280-a37a-11eb-8301-b4f1d6d5c4e2.png)

The screenshot shows you that the last status is a paid-status. Can you have a look?

**Comment by hreinberger** [comment]
Hi @carlos86 

I was able to track down this txid in our logs. This seems to be an authorized prepayment that was paid in two parts, though I can't dive deeper into this. Our platform can be a bit particular about prepayment and authorizations, so I'd advise you to contact our technical support with this issue. Our colleagues can go deeper into the transaction analytics with you and can raise an issue with us in case this is something we can fix in our plugin. You can reach them at tech.support[at]payone.com - be sure to tell them the txid or link to this issue.

**Comment by carlos86** [comment]
Hi @hreinberger, 

thanks. I just forwarded it.
