### ISSUE TITLE
Issue #348 is still not part of an official release

### ISSUE THREAD

**Issue by andreasberenz** [PAYONE-GmbH/magento-2#385]
After almost one year, I would expect, that this very important change is released.
Every time we need to redeploy the vendor files this "wrong bahaviour" in our case is deployed and we have to patch this.

https://github.com/PAYONE-GmbH/magento-2/commit/174542c776d6ce82be6378cf20294dc50390aa9c 

The commit message says, that it "needs further testing" but it was still selected for the release. In theory you have a solution, but you don't deploy it? Why? 

I know good reasons why, because there is no good migration path for that and if you deploy the configuration option, every installation is facing again a change in the behaviour.

I would be fine with, if you make a migration, which enables this option by default to keep the current behaviour and we're able to disable this option in our next release. But if the codes stays like that, we will always have this misbehaviour and the damage if this issue is out of our scope.

Writing a custom module for this case, which corrects this for us, must be double checked as well every time there is a new release.

**Comment by hreinberger** [comment]
unstaling this to investigate. We certainly need to fix this instead of keeping half-done code in here.
