### ISSUE TITLE
CC Card iframe Custom Styling Quotation marks not escaped correctly

### ISSUE THREAD

**Issue by davidverholen** [PAYONE-GmbH/magento-2#39]
If you save a css string containing double quotes (e.g. font-family: "some font", ....") in cc_template -> Standard Style -> input (for Example), the value is saved correctly and also the css works in frontend.

The Problem is, when the configuration is loaded again in the Magento Backend, the quotes are not escaped correctly and the value of the input field is empty.

Saving the configuration will then empty the value in the database and the custom styling is gone.

Current workaround for us: use single quotes.

**Comment by fjbender** [comment]
Can reproduce. @FATCHIP-GmbH to the rescue!
