### ISSUE TITLE
'Sequence No incorrect' after migration

### ISSUE THREAD

**Issue by NilsHansen** [PAYONE-GmbH/magento-2#390]
Hi all,
we have migrated our shop from magento1.9 to magento2.3.3 - after this process we cannot capture paypal orders. In the payone api log the error message is:

customermessage: Bei der Bearbeitung dieser Transaktion ist ein Fehler aufgetreten (Falsche Parameter).
errorcode: 907
errormessage: Sequence no incorrect
status: ERROR

The sequencenumber for this request is: 0 - Request: capture
In the docs the "0" is pre-authorization and not capture?!

Also we recognized, that the database table "payone_protocol_transactionstatus" is no longer filled... The last entry in this table is BEFORE migration... Is this table no longer needed in Magento2? Usually this table contains a database entry for every transaction.

Greetings
Nils

**Comment by jvarelmann** [comment]
hello Nils,

the database struction is different between Magento 1 and 2  yes ,
the sequence number is used for the history of a booking like capture 1 = seq.No. 0  capture 2 =seqNo 1 debit =seqNo. 3 and so on.
all the seqNo. are stored by the booking. It look like the Payone Modul in the Magento 2 cannot see this datas 
the only solution would be for the old bookings from the magento 1 shop to process this manually in the Payone Merchant Interface for the short period of transition

regards Juergen

**Comment by NilsHansen** [comment]
Hi Juergen,
sorry - our problem is with new orders. Done by magento2 & the current payone module. The "old" orders are captured in the old system (Magento1) before migration.

**Comment by jvarelmann** [comment]
Hi Nils 

sorry for the miss understanding. The sequence Number will be changed by the webhook. did you change the URL from <SHOPURL>/index.php/payone_core/transactionStatus    to <SHOPURL>/index.php/payone/transactionstatus in the Payone Account ?

regards Juergen

**Comment by NilsHansen** [comment]
Hi Juergen,
we fully installed magento2 blank, pulled the new module in via composer and then migrated our orders, customers and articles from magento1. So actually, its a new install of the module...

**Comment by jvarelmann** [comment]
Hello Nils,

I would like to help you. There is no known issue that there are problems the sequence Number. To check everything I need to have some more informations. Please send me via mail your MID , and the transaction ID and Magento version and Plugin version so I can have a look in our system. please send it directly to juergen.varelmann@payone.com

regards Juergen

**Comment by NilsHansen** [comment]
Hi all,
after changing the URL in the pmi from /index.php/payone_core/transactionStatus to /index.php/payone/transactionstatus the orders can now be captured!

Thanks to Juergen from Payone Tean
