### ISSUE TITLE
Vorkasse für die Schweiz: Adresse der Bank für die Einzahlung am Bankschalter in der Schweiz zwingend notwendig

### ISSUE THREAD

**Issue by carlosblackdd** [PAYONE-GmbH/magento-2#393]
Bei der Zahlart Vorkasse erhalten wir standardmäßig die folgenden Parameter im Callback: 

Accountholder:	XXXX
Accountnumber:	XXXXX
Bank code:	XXXXX
IBAN:	XXXXXX
BIC:	XXXXX
Bank:	UBS Switzerland AG
Payment reference:	XXXXX

Dies ist leider für die Schweiz unzureichend. 
Die Adresse der Bank ist für die Zahlart in der Schweiz zwingend notwendig. 

Leider erhalten wir derzeit mehrmals die Woche, dass Kunden am Bankschalter mit den Informationen abgewiesen werden. 
Als Fallback könnte man ggfs. die Adresse im Bank-Attribut mit aufnehmen. Das müsste jedoch von Ihnen geprüft werden.

**Comment by janteuber** [comment]
Wir haben den PR https://github.com/PAYONE-GmbH/magento-2/pull/410 soeben gemerged. Dieser wird dann im nächsten Release ausgerollt.
