### ISSUE TITLE
LogFile Location is root /var/ instead of Magento ./var/

### ISSUE THREAD

**Issue by riconeitzel** [PAYONE-GmbH/magento-2#394]
https://github.com/PAYONE-GmbH/magento-2/blob/2b348b9954c9f1516793bd8ec1df8eecd8fabfa6/Model/Logger/ForwardingLogger.php#L34

If you try to create a log in /var/log instead of ./var/log you'll most probably get stuck with "permission denied" problems.

The log - in our case - wasn't written. In our managed environment (maxcluster) write access is not allowed to /var/log/!

**Comment by hreinberger** [comment]
good catch, we'll deal with it!
