### ISSUE TITLE
Issue with closed payment page, no redirection to the shop, results in cancel of the order

### ISSUE THREAD

**Issue by DarekTw** [PAYONE-GmbH/magento-2#398]
Hello team,

We have noticed a strange behavior for Payone payments with redirection.
If the customer closes the payment page immediately after making the payment without returning to the shop success page, the order can be processed as usual.
The problem occurs when the customer returns to the shop some time later with the same session, then on the checkout page Payone module will close the last order in the checkout session.

We have several orders where the state and status are inconsistent, for example the `state` is `processing` and the `status` is `canceled` or even the `state` is `closed` and the `status` is `canceled`, meaning the order has already been processed.
The affected payment methods are payone_creditcard and payone_obt_sofortueberweisung.

The code responsible for this issue is \Payone\Core\Model\Handler\Cancellation this is an observer for event controller_action_predispatch_checkout_index_index

Expected:
The successful paid order should not be cancelled.

Magento ver. 2.4.2
Payone ver. 3.2.0

**Comment by janteuber** [comment]
Hello @DarekTw ,
Thank you for providing this topic.

I created an internal ticket to solve that problem.

**Comment by janteuber** [comment]
Hello @DarekTw ,
could you update our plugin to 3.4.1 please. Our agency told me, that we already fixed that issue in our newest version.
