### ISSUE TITLE
Klarna Invoice cartId error when logged in

### ISSUE THREAD

**Issue by Detzler** [PAYONE-GmbH/magento-2#404]
An error occurs when a logged in user clicks the Klarna Invoice button.

![Bildschirmfoto von 2021-10-23 15-10-34](https://user-images.githubusercontent.com/1556434/138557811-129a3246-e514-4195-938b-dec88f0a07bd.png)

Log entry:

`
Message: The current request does not expect the next parameters: cartId {"exception":"[object] (Exception(code: 0): Report ID: webapi-xxx; Message: The current request does not expect the next parameters: cartId at /vendor/magento/framework/Webapi/ErrorProcessor.php:208, UnexpectedValueException(code: 0): The current request does not expect the next parameters: cartId at /vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php:177)"} []
`

http call:

`
https://github.com/PAYONE-GmbH/magento-2/blob/v3.2.0/view/frontend/web/js/view/payment/method-renderer/klarna-method.js#L103
`

vendor/payone-gmbh/magento-2/etc/webapi.xml:

    <route url="/V1/guest-carts/:cartId/payone-startKlarna" method="POST">
        <service class="Payone\Core\Api\KlarnaHandlerInterface" method="startKlarnaSession"/>
        <resources>
            <resource ref="anonymous" />
        </resources>
    </route>

    <route url="/V1/carts/mine/payone-startKlarna" method="POST">
        <service class="Payone\Core\Api\KlarnaHandlerInterface" method="startKlarnaSession"/>
        <resources>
            <resource ref="self" />
        </resources>
        <data>
            <parameter name="cartId" force="true">%cart_id%</parameter>
        </data>
    </route>

Either the route definition is wrong or the parameters at http call are wrong.

Magento v2.4.3
php7.4

**Comment by Detzler** [comment]
Hello @hreinberger any news on this?

**Comment by hreinberger** [comment]
We'll have a look, thanks for pinging me!

**Comment by janteuber** [comment]
Hello,
we fixed that issue with https://github.com/PAYONE-GmbH/magento-2/pull/418
We will release our new plugin in the next days.
