### ISSUE TITLE
Payone Protect Boniversum Verita - gender and birthday are missing - consumerscore request   

### ISSUE THREAD

**Issue by knigbur** [PAYONE-GmbH/magento-2#407]
# Issue:
* 'gender' and 'birthday' are mandatory to return creditranking scores other than U or R.
* our plugin version is 3.2.0.
* proterct is used in producting and functional but only return definetly red Scores and Rest 'unknows'
* boniversum support has confirmed that the G an Y Scores are only returned if request includes gender and birthday

according to: https://docs.payone.com/pages/releaseview.action?pageId=1214564

* TPI-3635 is the internal  refernce we got from payone technical support)

**Comment by janteuber** [comment]
Hello @knigbur,
Thank you for set up an issue.

We fixed that and already released it in 3.4.x.

Regards
Jan
