### ISSUE TITLE
Missing field validation in request (id > 32 chars) leads to "wrong parameters"

### ISSUE THREAD

**Issue by netzkollektiv** [PAYONE-GmbH/magento-2#416]
If there is a product in the payment request having a SKU with length > 32 chars the API throws "1611 - Bei der Bearbeitung dieser Transaktion ist ein Fehler aufgetreten (Falsche Parameter).". Parameters should be validated and probably shortened by the API library to meet the API requirements.

Here is the example request assembled by the Payone module leading to this specific failure:

https://api.pay1.de/post-gateway/?mid=12345&portalid=543210&key=dgfdfhddhddhfhf&encoding=UTF-8&integrator_name=Magento2&integrator_version=2.4.0&solution_name=fatchip&solution_version=3.2.0&request=authorization&mode=live&aid=123456&reference=100000111&amount=3850&currency=EUR&firstname=Herr%C3%A9+&lastname=Muster+&street=Hauptstra%C3%9Fe+10&zip=12345&city=Stadtname+&country=DE&email=test%40gmail.com&telephonenumber=123456789&language=de&shipping_firstname=Herr%C3%A9+&shipping_lastname=Muster+&shipping_street=Hauptstra%C3%9Fe+10&shipping_zip=12345&shipping_city=Stadtname+&shipping_country=DE&clearingtype=sb&onlinebanktransfertype=PNT&bankcountry=DE&iban=DE123456789123456700&bic=BIC12345&successurl=https%3A%2F%2Fdomain%2Fde%2Fpayone%2Fonepage%2Freturned%2F%3FincrementId%3D100000111&errorurl=https%3A%2F%2Fdomain.de%2Fpayone%2Fonepage%2Fcancel%3Ferror%3D1%2F&backurl=https%3A%2F%2Fdomain.de%2Fpayone%2Fonepage%2Fcancel%2F&id[1]=gg10014-16190-0406-16653-2311-16692&pr[1]=3850&it[1]=goods&no[1]=1&de[1]=PRODUCTNAME&va[1]=0

**Comment by jvarelmann** [comment]
Hello,

thanks for the information I will pass it over to our developer

regards Juergen

**Comment by jvarelmann** [comment]
Hello,

the error should be rolved in plugin version 3.3.0

regrads Juergen

**Comment by netzkollektiv** [comment]
Thanks @jvarelmann for taking care of this - however, we are currently using payone-gmbh/magento-2 @ v3.2.0 and we are having the issue as described above.

**Comment by netzkollektiv** [comment]
@jvarelmann Thanks, forget my last comment.
