### ISSUE TITLE
Checkout-Agreements not working

### ISSUE THREAD

**Issue by josefbehr** [PAYONE-GmbH/magento-2#42]
We tried replacing an existing extension by a third-party developer by this official one and encountered a problem with the agreements when placing the order.
It doesn't matter if the boxes are checked or not, as (using this extension and a payment method provided by it) the data about them being checked is not transmitted anymore (see payload on request to V1/cart/mine/payment-information, "extension_attributes" are nowhere to be found, even though this is a core Magento functionality).
I assume this is a bug, as the extension seems to be relatively new and untested. Please get back to me about the state of the issue and if/when we can expect a solution. For mail, please use behr [ät] basecom [DE]

**Comment by josefbehr** [comment]
![payone-m2-err](https://cloud.githubusercontent.com/assets/4368880/23405008/53185938-fdb8-11e6-9798-8a9a7b2acc29.png)

**Comment by josefbehr** [comment]
Hi, thanks for the quick fix.
Unfortunately - although I'm not totally sure it's related - we now get an error when clicking the "Same adress for billing and shipping" checkbox in the payment step (even when it's pre-selected). Didn't have this error before:
![payone-m2-2](https://cloud.githubusercontent.com/assets/4368880/23546447/e2f40324-ffff-11e6-944e-08efd8ab7c4c.png)

**Comment by fjbender** [comment]
I can't reproduce this on my end, unfortunately.
