### ISSUE TITLE
Update composer.json version

### ISSUE THREAD

**Issue by ersvltan** [PAYONE-GmbH/magento-2#422]
Hi,

We are having problems updating the module in our magento system.

![image](https://user-images.githubusercontent.com/29982255/152318682-62806be5-c59f-4589-94f8-31e13919c8a9.png)

Could you please update the version in composer.json?

Thank you!

**Comment by janteuber** [comment]
Hallo @ersvltan ,
Thanks for your hint.

We released the 3.4.1: https://github.com/PAYONE-GmbH/magento-2/releases/tag/v3.4.1
