### ISSUE TITLE
CVC is not required, even if Check Card Validation Code is set to Yes

### ISSUE THREAD

**Issue by mfickers** [PAYONE-GmbH/magento-2#425]
We are using v3.3.0 of this extension in a Magento 2.4.2-p1, but I've also tested this with v3.4.1 and Magento 2.4.3. CVC validation is enabled. Unfortunately it is still possible to place an order using Payone credit card as payment method without supplying the card's CVC.

Validation works as expected as long as something is entered in the validation code field. Incorrect length or invalid characters are not allowed and result in an error message. But when leaving the field blank, there is no validation at all and it is possible to complete the order.

### Prerequisites
* Enable PAYONE Credit Card
* Enable Check Card Validation Code

### Steps to reproduce
* Add a product to card
* Proceed to checkout
* Enter shipping information and proceed to payment step
* Select PAYONE Credit Card as payment method
* Enter cardholder, card number, expiration date. Leave validation code field empty
* Place Order

### Expected result
* Order is not placed
* Error message notifying the user that the validation code is required

### Actual result
* Order is placed

**Comment by janteuber** [comment]
Hello @mfickers ,

Thank you very much for your message.

Did you notice this behavior in test or live mode?

In test mode, this behavior is wanted.

**Comment by mfickers** [comment]
This behavior is the same for both modes. I've tested in live mode for v3.3.0 on Magento 2.4.2-p1 and in test mode for v3.4.1 on Magento 2.4.3.

Just to be clear, I'm not talking about the test mode accepting any three digit number as a valid validation code, but specifically an empty input field not resulting in an error.

**Comment by janteuber** [comment]
Hello @mfickers ,
I could reproduce your issue and created a ticket. We will provide a fix in our new plugin version (End of May 2022)

**Comment by torhoehn** [comment]
@janteuber I think this issue shouldn't be closed until the fix is released, because the problem still exists. Personally I think End of May is really late for such a security relevant feature.

**Comment by janteuber** [comment]
Hello @torhoehn @mfickers ,
we merged the fix for that issue: https://github.com/PAYONE-GmbH/magento-2/pull/438 and will release it in our new plugin version (End of May 2022)
