### ISSUE TITLE
Placeholders aren't shown in Admin

### ISSUE THREAD

**Issue by torhoehn** [PAYONE-GmbH/magento-2#426]
In the Admin it isn't possible to see possible placeholders for input fields, e. g.:
```
    <field id="narrative_text" translate="label,comment" type="textarea" sortOrder="485" showInDefault="1" showInWebsite="1" showInStore="1">
        <label>Narrative Text</label>
        <comment>Maximum 81 digits. Placeholders: {{order_increment_id}}</comment>
    </field>
```
<img width="608" alt="Screenshot 2022-03-02 at 20 23 57" src="https://user-images.githubusercontent.com/1945725/156434027-941d3cb0-5330-402b-ae38-009be1617dde.png">

Installed Payone module version: 3.3.0
Magento version: 2.4.2-p1 with applied patches for MDVA-43395 and MDVA-43443

**Comment by janteuber** [comment]
Hello @torhoehn ,
Can you please describe in more detail where exactly this field is, what exactly is not possible, what you expect? Where exactly is the added value for a merchant?

**Comment by torhoehn** [comment]
@janteuber Sorry, but don't understand why I have to describe the value for the merchant. My code example is something out of this extension, so it's something you already wanted to show.

**Comment by janteuber** [comment]
Hello @torhoehn ,
As mentioned above, I need your specification on this issue. Thank you very much.

**Comment by torhoehn** [comment]
@torhoehn The placeholder should be displayed in the admin (see comment under the textarea), otherwise it's not possible to configure the module properly, because the possible placeholders aren't known.

**Comment by torhoehn** [comment]
@janteuber Any update on this?

**Comment by janteuber** [comment]
Apparently the Magento2 framework prevents the use of double curly braces in language snippets.

Changed the placeholders to single curly brackets everywhere now - so they can be displayed there.

Old configurations with double curly brackets still work though.

Robert also noticed during testing that the "Dynamic refund message" was not used for the refund as expected, but the "Dynamic invoice message".
He has also fixed this here.

**Comment by janteuber** [comment]
@torhoehn I I have just merged the PR: https://github.com/PAYONE-GmbH/magento-2/pull/457
