### ISSUE TITLE
Creditcard cardholder is not saved for first entry

### ISSUE THREAD

**Issue by mfickers** [PAYONE-GmbH/magento-2#428]
When saving the credit card data for the first card of a user, the cardholder information will not be saved. When visiting the checkout afterwards, there will be a blank space where the cardholder's name should appear.

This does not occur on additional saved cards.

See attached screenshot, the first card has the name of the cardholder missing, while it is displayed for the second card:

![Bildschirmfoto 2022-02-14 um 10 50 15](https://user-images.githubusercontent.com/12683535/156619511-26cd4aed-d220-4c0f-91e6-8f0bdcc87b38.png)

### Prerequisites
* PAYONE Creditcard payment method enabled
* Configuration "Creditcard-management enabled" set to Yes

### Steps to reproduce
* Log in to an account without saved credit cards
* Add a product to cart
* Go to checkout
* Enter shipping information, select shipping method
* Proceed to step 2
* Select PAYONE Credit Card as payment method
* Enter credit card data
* Select checkbox "Save the payment data for future use."
* Place order

### Expected result
* Credit card data is saved fully

### Actual result
* Cardholder is missing from saved credit card data

**Comment by janteuber** [comment]
Hello @mfickers ,
Thank you very much for providing us the PR.
We will test and check the PR. After that, I'll be happy to give you feedback from our developers. Until then I would leave the issue open.
