### ISSUE TITLE
Double Invoice Creating for the Paid Order with Credeit Card payment

### ISSUE THREAD

**Issue by shoaibgits** [PAYONE-GmbH/magento-2#430]
We are running Magento 2.4.2 and with the latest version of Payone-Magento2 Extension, Previously we faced the same issue where multiple invoices were creating for a single order based on the Response back from Payone API, but we have still noticed and it happening in case of credit card payment , where order first get payed and then again it goes in pending state.

Please check the following screenshot attached, due to this issue, orders are not going into Complete state and some ERP importing stuff is getting disturbed due to this.

Please check if there is still an update we have to do on code level, or any settings required to be changed?

![image](https://user-images.githubusercontent.com/26060844/157652291-13804f69-b7d7-48d6-8432-8d55d2c2c339.png)

Also Attached the API response screenshot here, please check it too for more understanding of the issue!

![image](https://user-images.githubusercontent.com/26060844/157652668-d2185429-ca07-4116-86f4-17723071fc28.png)

Thanks!

**Comment by janteuber** [comment]
Hello @shoaibgits ,
Please write this in an email, please mention the merchant ID of the merchant and send it tech.support@payone.com. The colleagues need to take a close look at the order here. I am pretty sure that there is no general error in the Magento plugin.
