### ISSUE TITLE
Birthday is not validated correctly

### ISSUE THREAD

**Issue by torhoehn** [PAYONE-GmbH/magento-2#434]
While using PAYONE - Paysafe Pay Later™ Invoice we discovered that the birthday is not validated correctly.

The validation is implemented here: https://github.com/PAYONE-GmbH/magento-2/blob/master/view/frontend/web/js/view/payment/method-renderer/base.js#L106

E.g. it returns `true` for the following input:
`isBirthdayValid('32', '13', '75');`

**Comment by janteuber** [comment]
Hello @torhoehn ,

Thank you for your message and also for your PR.

I will have our agency check this and give you feedback.

**Comment by janteuber** [comment]
Hello @torhoehn ,
We checked your PR and merged it. Thank you very much.
Next release will be in May.
