### ISSUE TITLE
Country in order confirmation mail not translated properly

### ISSUE THREAD

**Issue by magex55** [PAYONE-GmbH/magento-2#437]
In a 2 store view (DE/EN) 2.4.2 store the country in the order confirmation mail ist not translated properly. Its in German even though its supposed to be translated to English. We are running version 2.8.0 of the extension. 

Any advice? Will an update to 3.4.1 solve this?

**Comment by janteuber** [comment]
Hello @magex55 ,
We are not aware of this behavior. Since the version you are using is very old, the first thing I would recommend is to update to the latest version.
