### ISSUE TITLE
Specific Products Are Throwing Error Of Invalid Parameters while checkout with Payone PayPal

### ISSUE THREAD

**Issue by shoaibgits** [PAYONE-GmbH/magento-2#456]
There is specific product as same like others but Payone Paypal is throwing error of invalid parameters for that. this only happening through the Payone Paypal. I have tried Magento Express Paypal and it was working fine, 

Can you please check how this come., and let me know what is missing from parameters,

![image](https://user-images.githubusercontent.com/26060844/171113513-dc7c785c-ce4f-4c5a-9d78-3a17d8339ab6.png)

Thanks!

**Comment by janteuber** [comment]
Hello @shoaibgits ,

Could you please send this case by mail to our tech-support team (tech.support@payone.com). Please send your mid and a timestamp when this error occurred. Our colleagues will have a look into the logs why this error occurred.

I assume that this is not a general problem in the plugin and therefore I will close the issue for now.
