### ISSUE TITLE
Unclear logic with addtocart.shortcut.buttons

### ISSUE THREAD

**Issue by clicks-kodet** [PAYONE-GmbH/magento-2#459]
According to: 
https://github.com/PAYONE-GmbH/magento-2/blob/d343e22cb6c8bd6b3db2bfc74ece52e6f6851356/Observer/AddPaypalExpressButtons.php#L71

the button will not be rendered in case there is already a block `\Magento\Catalog\Block\ShortcutButtons` with name `addtocart.shortcut.buttons` or `addtocart.shortcut.buttons.additional` in the current layout. Why?

The default template contains this block and that case the button would never be rendered. I'd completely understand if the `if` would be negated 

```
if (!in_array($shortcutButtons->getNameInLayout(), ['addtocart.shortcut.buttons', 'addtocart.shortcut.buttons.additional'])) {
```
as in such case you couldn't render it into block which doesn't exist and you intend to use it.

Could you explain me the current logic behind the `if` statement?

**Comment by janteuber** [comment]
Hello @clicks-kodet ,

Thanks for your message.

I will contact the developer directly for this. As soon as I have new information I will share it here.
