### ISSUE TITLE
Unable to make payment using API

### ISSUE THREAD

**Issue by hemendraajmera** [PAYONE-GmbH/magento-2#460]
I am using react as frontend for website and store features, i want to make payment using API.
Is there any API document for payone for using in magento2.
I am stacked to make payment 

can you please share document or example for how to use this API??

**Comment by janteuber** [comment]
Hello @hemendraajmera ,

attached our complete API documentation: https://docs.payone.com/

For further technical questions about the API, please contact tech.support@payone.com.
