### ISSUE TITLE
Customer Data is not initialized on invalidate call

### ISSUE THREAD

**Issue by a-litvin** [PAYONE-GmbH/magento-2#464]
In _view/frontend/templates/redirect_return.phtml_ in line 33 we have a customerData::invalidate call:
`customerData.invalidate(['cart', 'checkout-data']);`
Now sure about how it works in clear Magento, but we have an issue in our Magento 2.4.3 and Amasty One Step Checkout. The reason is that customerData object is not initialized at this moment, that means, a storage is also not initialized and _customer-data.js_ fails on line 178 on _storage.remove_ call.

The issue may be fixed by wrapping the code by _customerData.getInitCustomerData().done()_ construction. It might look like:

`
if (typeof customerData.getInitCustomerData === "function") {
            customerData.getInitCustomerData().done(function () {
                redirectCancellation(customerData, checkoutData);
            });
        } else {
            redirectCancellation(customerData, checkoutData);
}`

**Comment by hreinberger** [comment]
Hi and thanks for raising this issue. We'll have a look at it!

**Comment by FatchipRobert** [comment]
Hello @a-litvin , based on your comment I developed a change here:
https://github.com/PAYONE-GmbH/magento-2/pull/466

Does this fix your issue?

**Comment by a-litvin** [comment]
Hi @FatchipRobert

As I remember the fix we did on our site is exactly the same :)
