### ISSUE TITLE
With discount order place not working

### ISSUE THREAD

**Issue by sanjay-evrig** [PAYONE-GmbH/magento-2#473]
https://github.com/PAYONE-GmbH/magento-2/blob/master/Helper/AmastyGiftcard.php#L52 it require two parameter and passed only one parameter at https://github.com/PAYONE-GmbH/magento-2/blob/master/Helper/AmastyGiftcard.php#L84

**Comment by janteuber** [comment]
Hello @sanjay-evrig ,

Thank you very much for your message.

We have created a fix for this: https://github.com/PAYONE-GmbH/magento-2/pull/474
