### ISSUE TITLE
Amazon Pay not showing up as payment method with Magento 2.4.5

### ISSUE THREAD

**Issue by alextd08** [PAYONE-GmbH/magento-2#477]
Magento 2.4.5 
php 8.1
payone 3.6.0

HI, 
AmazonPay is not showing as payment method in the list (default checkout) - all other payment methods are showing!
In the Mini-Cart the Amazon-Button is showing.

Thanks
Alex

**Comment by janteuber** [comment]
Hello @alextd08 ,

Thank you for your message.

This is not bug indeed, it is implemented exactly like this. The reasons lie in the technical restrictions of the implemented interface.

For the year 2023 we plan to change to the current Amazon interface. The payment method will then also be implemented in the checkout.
