### ISSUE TITLE
Creditcard logos

### ISSUE THREAD

**Issue by skymeissner** [PAYONE-GmbH/magento-2#48]
PAYONE merchant service told me that it is mandatory to add creditcard logos on the payment page. Instead of the merchant the extension itself should take care of this.

**Comment by fjbender** [comment]
Agreed. We'll look into this, however, please do not expect too quick results as there are quite some things to take into account (for instance, we don't want to release a new version whenever a payment method logo changes).

**Comment by hreinberger** [comment]
sooooo after further consideration we decided to not implement this. We could have used some kind of CDN for the delivery, but some merchants actually use monochrome versions of the logos or show them on other sites. For us it seems like we can't offer a sweet solution for all merchants, so there's always need for customization. We offer the logos for download on our site here though for easy access: https://www.bspayone.com/DE/de/downloads
