### ISSUE TITLE
Missing handling of region-codes (Magento/ISO vs. Payone api)

### ISSUE THREAD

**Issue by berwa** [PAYONE-GmbH/magento-2#480]
Hello Payone-Team,
we recently ran into the following problem within one of our projects: 
The customer can not continue or complete the checkout, as his address from Argentina is rejected by the Payone server/api with the message _Parameter {state} faulty or missing_.
The data transferred as _state_ was _AR-X_, which is the same code that is used in Magento, and that is created during the Magento-installation: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Directory/Setup/Patch/Data/AddDataForArgentina.php#L72
From the information publicly available _AR-X_ (and the other state/region-codes used by Magento for Argentina) are the proper ISO 3166-2 codes (https://www.iso.org/obp/ui/#iso:code:3166:AR), but the Payone api expects different ones (https://docs.payone.com/pages/releaseview.action?pageId=1213957#ISOSubdivisions(ISO31662)-AR-Subdivisions).

According to a quick check the same issue is also present for state/region-codes for China, Magento (https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Directory/Setup/Patch/Data/AddDataForChina.php#L63) and ISO 3166-2 (https://www.iso.org/obp/ui/#iso:code:3166:CN) use a CN-_letter_ combination, whereas the Payone api expects a numeric code (https://docs.payone.com/pages/releaseview.action?pageId=1213957#ISOSubdivisions(ISO31662)-CN-Subdivisions).

In my opinion the Payone extension should make sure that the state/region-codes are transmitted to the Payone api/server as specified in the Payone documentation and thus convert the codes from Magento accordingly.

Best regards

**Comment by janteuber** [comment]
Hello @berwa ,

Thank you very much for your advise.

We will check that topic asap.
