### ISSUE TITLE
when selecting credit card type showing error

### ISSUE THREAD

**Issue by hemendrametawolf** [PAYONE-GmbH/magento-2#481]
when i am changing card type it will showing below error Uncaught TypeError: Cannot read properties of undefined (reading 'maxlength')
![Screenshot from 2022-11-11 16-05-11](https://user-images.githubusercontent.com/114897672/201323762-d51353df-82ce-482b-8af1-ce29d9b35f5a.png)

**Comment by janteuber** [comment]
Hello @hemendrametawolf ,
Thank you very much for your message.
Is it possible that there was still an entry in the credit card number field? If you delete the credit card number before you change the credit card type, the error should not occur.
In this field we check if the credit card number matches the credit card type.

**Comment by hemendrametawolf** [comment]
It will showing when we go to checkout cart without providing any details.

**Comment by janteuber** [comment]
Please write an email to tech.support@payone.com with your shop name, your MID and please briefly describe the problem. Then we will take a closer look at it.
Thank you.
