### ISSUE TITLE
Magento2 dont have option to map paid to processing

### ISSUE THREAD

**Issue by hemendrametawolf** [PAYONE-GmbH/magento-2#484]
As M1 have status mapping option where we can map paid status to magento2 order status processing. but in magento2 there is no option avaialbe in drown, i am unable change status when amount is paid using payone credit card 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/114897672/206422512-99522571-4fd4-47d0-8791-137bd4b38d4b.png)

Can you help me on that how i can manage this status mapping

**Comment by janteuber** [comment]
Hello @hemendrametawolf ,

Thank you for your message.

We do not have a webhook with the status "pending". Therefore you don't need this status mapping.
