### ISSUE TITLE
Facing multiple issue after integrate payone

### ISSUE THREAD

**Issue by hemendrametawolf** [PAYONE-GmbH/magento-2#487]
1. when provide card details as 
4111111111111111
John deo
6/25
cvv not asking as 
 it showing error as Please enter the credit card data completely.
 
![image](https://user-images.githubusercontent.com/114897672/208887559-3db278ac-28a7-47a1-b8cf-424577cfba74.png)

2. when i try to place order showing that 
Following products with requested ids were not found:
can you please help me why this kind of issue happen. Is there any configuration issue or anything need to change on payone side.

Thanks in advance.

**Comment by hreinberger** [comment]
Hi @hemendrametawolf 

could you write an email to our tech support staff at tech[dot]support[at]payone[dot]com? You can refer to this issue and please also give them your merchant ID. Our colleagues can then have a look at the API logs and check your shop config with you. Thanks!

**Comment by hemendrametawolf** [comment]
Already share the same on email tech[dot]support[at]payone[dot]com.
