### ISSUE TITLE
Facing multiple issue after integrate payone

### ISSUE THREAD

**Issue by hemendrametawolf** [PAYONE-GmbH/magento-2#488]
No tech support reply on email which i sent for the support.I am continue follow-up on that, i already mentioned that due to payone issue i am unable to move to production.
Please help and support to fix the issues ASAP.

Let me know if we can connect over call to check and fix that issue.

**Comment by janteuber** [comment]
Hello @hemendrametawolf ,

Thank you very much for your message.

Please note that we do not accept support requests via github.

Please contact us at tech.support@payone.com

Thank you very much.
