### ISSUE TITLE
Adding PHP 8.2 support for Magento 2.4.6 release

### ISSUE THREAD

**Issue by Sharkozp** [PAYONE-GmbH/magento-2#495]
Hi, 

It will be new release on 14.03.2023 for Magento - 2.4.6 with PHP 8.2 support. 

- https://experienceleague.adobe.com/docs/commerce-operations/release/versions.html?lang=en

I have tested beta version for Magento 2.4.6 with PHP 8.2 and yours module not support PHP 8.2 in composer.json. Maybe there also must be added changes in code

Best Regards,
Oleksandr

**Comment by janteuber** [comment]
Hello @Sharkozp ,

Thank you for your message.

I'll be glad to pass your info to our developers. As soon as the new version is released, we will adjust our plugin immediately.
