### ISSUE TITLE
deprecated _isScopePrivate in Totals.php

### ISSUE THREAD

**Issue by Leszek-mediawave** [PAYONE-GmbH/magento-2#499]
Hi,

we noticed usage of deprecated functionality: "$this->_isScopePrivate = true;" in Block/Onepage/Totals.php

according to magento documentation 
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/cache/page-caching/private-content.html

"Do not use the $_isScopePrivate property in your blocks. This property is obsolete and will not work properly."

would it be possible to fix this?

Best regards

**Comment by janteuber** [comment]
Hello @Leszek-mediawave ,

Thank you very much for your message.

A developer will take a look at your findings.

**Comment by janteuber** [comment]
We have removed the _isScopePrivate usage and created the functionality we wanted there via something else.

The display block where this came into play is used with the PayPal Express/AmazonPay order summary.

**Comment by Leszek-mediawave** [comment]
Thank you
