### ISSUE TITLE
js error in checkout payment step

### ISSUE THREAD

**Issue by davidverholen** [PAYONE-GmbH/magento-2#5]
Magento 2.1.2 + sample data + payone module (dev-master)

In the payment step of the checkout I get a js error:
```payone_iframe_min.js:8 Uncaught TypeError: Cannot read property 'hasOwnProperty' of null(…)```

Still making an order (tested cc and paypal) seems to work, but this could break other js functionalities on the site
![checkout-js-error](https://cloud.githubusercontent.com/assets/2813693/20053036/04bc8a64-a4d7-11e6-94d1-8e7359eb4db6.PNG)

**Comment by fjbender** [comment]
Doesn't seem to be a bug in the module at first sight (``payone_iframe_min.js`` is delivered by our platform and not the module), but maybe we transmit wrong/empty parameters.

**Comment by fjbender** [comment]
@davidverholen Pinned it down. The Magento 2 extension injects the "Please select" into our iFrame which isn't recognized properly in the JS on our side (which we will fix).

We'll deliver the updated ``payone_iframe_min.js`` automatically as soon as it's fixed, no update of the module necessary.

**Comment by Bugfighter** [comment]
@fjbender nicely debugged!
