### ISSUE TITLE
Credit card payment after canceling payment process still authorized and order status processing

### ISSUE THREAD

**Issue by re-mxp** [PAYONE-GmbH/magento-2#503]
Hello,

Used:
* Magento version 2.4.5-p1
* PAYONE extension 3.6.0
* Pixi Magento Connector Extension 3.1.5

Problem is the following. When you make a credit card payment via PAYONE, you are redirected to a PAYONE 3D-Secure mask. If you click on 'Cancel' in this screen, you will be redirected back to the checkout process. Although the order is not completed, it is imported into Magento with the status `processing` and following comment:
`Authorized amount of ... €. Transaction ID: "..."`.

In PAYONE itself it correctly says that no successful 3D Secure process has taken place. Here the order status history:
```
29.03.2023 14:25:30 Processing Kunde Nicht benachrichtigt
Status changed to: processing (HAL)

29.03.2023 14:18:45 Canceled Kunde Nicht benachrichtigt
Pixi Export Status geändert zu "bestätigt"

29.03.2023 14:18:45 Canceled Kunde Nicht benachrichtigt
Pixi Export Status geändert zu "exportiert"

29.03.2023 14:18:16 Processing Kunde Nicht benachrichtigt
Autorisierter Betrag von ... €. Transaktions-ID: "..."
```

**Comment by jvarelmann** [comment]
Hello,

I just treid to rebuild this. where do you find this data in the backend or in the database ?

regards Juergen
