### ISSUE TITLE
PayPal Express Button does not respect Minimal Order Amount

### ISSUE THREAD

**Issue by nige-one** [PAYONE-GmbH/magento-2#525]
Hi,

coming from another problem I've found out, that the potential rendering of the Paypal (and others?) Express Button does not respect the configured minimal order amount. It will always be rendered. In the Luma checkout the Paypal checkout method is not shown.

**Comment by janteuber** [comment]
Hello @nige-one ,

Unfortunately, we cannot reproduce this behavior. Please give us more information on how we can reproduce the case. Please send the information to tech.support@payone.com.

Thank you very much.
