### ISSUE TITLE
Support of PHP 8.3

### ISSUE THREAD

**Issue by mfickers** [PAYONE-GmbH/magento-2#549]
[Magento 2.4.7 supports PHP 8.3](https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/system-requirements).

composer.json of this extension currently does not allow installing with PHP 8.3.

**Comment by jvarelmann** [comment]
Hello,

thats true because it is not tested right now , but it is on the list will be availible in the next release

**Comment by mfickers** [comment]
Any update on this? When can we expect the next release?

**Comment by janteuber** [comment]
Hello @mfickers ,

We have created a PR for it: [https://github.com/PAYONE-GmbH/magento-2/pull/555](https://github.com/PAYONE-GmbH/magento-2/pull/555)
We will release a new plugin probably next week.

**Comment by jg-development** [comment]
+1 ... need this asap

**Comment by jg-development** [comment]
it seems 3.12.0 resolved this issue .... thx. we can close this issue.

**Comment by janteuber** [comment]
We released last week the version 3.12.0, which is compatible with 8.3
