### ISSUE TITLE
CSP- Probleme: Unzer Ratenkauf

### ISSUE THREAD

**Issue by carlosblackdd** [PAYONE-GmbH/magento-2#554]
Wir haben ein Problem mit der Content Security Policy (CSP) in unserem Checkout-Prozess, wenn wir das Unzer Ratenkauf-Modul nutzen. Trotz einer umfassenden CSP-Whitelist und der Freigabe aller Payone-Inline-Skripte mittels Hash-Werten, erhalten wir weiterhin einen CSP-Fehler. Dieser tritt auf, wenn ein Kunde im Checkout einen der übermittelten Ratenpläne auswählt. Der Fehler führt zu einem Redirect auf die Startseite, was den Bestellprozess unterbricht.

**Schritte zur Reproduktion:**

Gehe zum Checkout-Prozess und wähle Unzer Ratenkauf als Zahlungsmethode.
Wähle einen der angebotenen Ratenpläne aus.
Beobachte den CSP-Fehler in der Browser-Konsole und den anschließenden Redirect zur Startseite.

**Erwartetes Verhalten:**

Der Kunde sollte den Ratenkauf ohne CSP-Verletzung und ohne Redirect auf die Startseite abschließen können.

**Tatsächliches Verhalten:**

Bei der Auswahl eines Ratenplans tritt ein CSP-Fehler auf, der zu einem Redirect auf die Startseite führt, wodurch der Checkout abgebrochen wird.

**Fehlermeldungen:**

Die genaue CSP-Fehlermeldung:
`
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src assets.adobedtm.com *.adobe.com www.googleadservices.com www.google-analytics.com googleads.g.doubleclick.net analytics.google.com www.googletagmanager.com *.newrelic.com *.nr-data.net geostag.cardinalcommerce.com 1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com 1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com includestest.ccdc02.com www.paypal.com www.sandbox.paypal.com www.paypalobjects.com t.paypal.com s.ytimg.com www.googleapis.com vimeo.com www.vimeo.com *.vimeocdn.com *.youtube.com https://www.gstatic.com/recaptcha/ https://www.google.com/recaptcha/ js.braintreegateway.com assets.braintreegateway.com c.paypal.com pay.google.com api.braintreegateway.com api.sandbox.braintreegateway.com client-analytics.braintreegateway.com client-analytics.sandbox.braintreegateway.com *.paypal.com songbirdstag.cardinalcommerce.com *.etermin.net *.ccm19.de *.facebook.net *.google.com *.googleapis.com *.babysmile24.com cdn.babysmile24.de cdn.babysmile24.at cdn.babysmile24.ch *.avada.io secure.pay1.de d.ratepay.com static-eu.payments-amazon.com x.klarnacdn.net cdn.klarna.com jsctool.com d.payla.io 'self' 'unsafe-eval' 'unsafe-hashes' 'nonce-MWFxdTB2eWJoNDh4NWJjb2dnOWhybTc1eTVsc25qMnY=' 'sha256-W5akSSK6LD5BjIlNICMcXaUObQSRAaj6bs7JHADURBA=' 'sha256-3qVqeAdyxxTdPkkRzqapjGkAUYLahxSrB7Mdup+GPQ0=' 'sha256-2rvfFrggTCtyF5WOiTri1gDS8Boibj4Njn0e+VCBmDI=' 'sha256-p8MCfMHqrovsjRYU9z0bU17dd0z81k/fVbGrtBBiM9g=' 'sha256-0pk2s4oXwBELlC6IBVb3nNaM2PjfjwI2N6OGIX5lx8Y=' 'sha256-nkEZknO0IxNxY/CkTMBhjNhwPvglpYumjx31B4fjkY8=' 'sha256-0Qiyps7OTbXMiBtvGsibX1djo3slWpHGfyulu0eWlZo=' 'sha256-TcUB1mzXiQO4GxpTRZ0EMpOXKMU3u+n/q1WrgVIcs1I=' 'sha256-3KfNjjRc5tPMdV0KK84boCNikOj1RbvG1NWFjVMedoM=' 'sha256-N1UWczU/APcqwgU81Z1sgv6sywtP+/Scibxb7tdJhks=' 'sha256-OvZj7S8rgJVfLDqSoV4CZ94uiTWqHNjDMboxW9/py0Q=' 'sha256-JFo3sED7f1Ev2ayJMEUoa7iTV0eqjShNvGG4kC/sbK4=' 'sha256-7rErpZZuzAjRc1f5G+qBHcX99BZcoMZpJBhqs+M/iBI=' 'sha256-r2g0WvOCYG6H5/6qX3gGNCpyCINxyrqg/Y98Qok1DgU=' 'sha256-T+5k/497be7qs7j1QLJuDXw/9NSxbLS+XvPYmI6fHI8=' 'sha256-...'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by carlosblackdd** [comment]
Das Problem liegt gefühlt hier in dem Bereich: 
https://github.com/PAYONE-GmbH/magento-2/blob/596c20ac75feca3c7668ffefa46194f359e7a7eb/view/frontend/web/js/view/payment/method-renderer/payolution_installment-method.js#L164

**Comment by janteuber** [comment]
Wir haben das CSP-Problem bereits in einem PR gelöst: https://github.com/PAYONE-GmbH/magento-2/pull/552

Diesen werden wir mit der nächsten Pluginversion veröffentlichen.

**Comment by carlosblackdd** [comment]
Ah super. Steht schon fest, wann es die neue Version geben wird?

**Comment by janteuber** [comment]
Auf jeden Fall in den nächsten Wochen. Der Entwickler ist aktuell noch dran die Kompatibilität zu PHP 8.3 herzustellen. Wenn das geschehen ist, wird das Plugin final gestestet und dann veröffentlicht.
