### ISSUE TITLE
Deprecated Functionality: hash_hmac(): Passing null to parameter #3 ($key) of type string is deprecated in /vendor/payone-gmbh/magento-2/Helper/Toolkit.php on line 272

### ISSUE THREAD

**Issue by darektw** [PAYONE-GmbH/magento-2#561]
After upgrading to Magento 2.4.7 we experience the following issue

main.CRITICAL: Exception: Deprecated Functionality: hash_hmac(): Passing null to parameter #3 ($key) of type string is deprecated in /vendor/payone-gmbh/magento-2/Helper/Toolkit.php on line 272

The NULL value is returned by the function `$this->getConfigParam('key')` here https://github.com/PAYONE-GmbH/magento-2/blob/master/Helper/Request.php#L125

**Comment by FatchipRobert** [comment]
I added a fix so that this error can not occure anymore.

But the error also implies that you have not configured a security key in the backend (or configured an empty security key).
This should never be the case because the module can not work that way.
