### ISSUE TITLE
Request for TWINT Payment Method

### ISSUE THREAD

**Issue by carlosblackdd** [PAYONE-GmbH/magento-2#567]
Hi PAYONE Team,

We’d like to request the addition of TWINT as a payment method in the PAYONE Magento 2 module. As we understand it, PAYONE already has a partnership with TWINT, but this payment method has not yet been implemented in the Magento 2 integration. TWINT is widely used and preferred in Switzerland, so including it would greatly benefit both merchants and end-users in that region.

Thank you for considering this feature request. We’d appreciate any feedback on the feasibility or timeline for adding TWINT support.

Thanks

**Comment by bw610** [comment]
Hello,

I support carlosblackdd's request. We also want to introduce the TWINT payment method in our online stores and have integrated all other payment methods via PAYONE so far. 
Perhaps you can give us a short-term estimate of when a final implementation could take place, if it does.

Thanks in advance
Benjamin

**Comment by jvarelmann** [comment]
Hello,

sorry to say this , but Twint is not implemented on our API and there are no plans at the moment to add it

regards Juergen

**Comment by carlosblackdd** [comment]
Hi Jürgen,

Thanks for pointing that out. I did see this, but it’s actually related to a different partnership paywithcharly
[https://www.payone.com/DE-de/ueber-uns/partner/handelsverband-deutschland]
Sorry. 

Maybe something to keep in mind for future reference.

Best,
