### ISSUE TITLE
Payment method invoice / Order and invoice paid immediately

### ISSUE THREAD

**Issue by skymeissner** [PAYONE-GmbH/magento-2#57]
Steps to reproduce:

1. Install a fresh Magento 2.1.5 (or 2.1.6) with sample data
2. Create a customer 
3. Create an order using payment method "payone_invoice", authorization method "authorize"  and payone mode "test".
3. Do not pay

Expected result:
1. An order is created, total paid is 0, total due is full amount
2. An invoice is created, status is unpaid

Actual result: 
1. An order is created, total paid is full amount, total due is 0
2. An invice is created, status is unpaid

Method "authorize" captures the invoice and by default Magento creates the invoice paid (due to US workflow where an invoice is generated AFTER payment). But for me this is to be rather unexpected, I use PAYONE to tell me whether and if an invoice is paid and I believe this is the usecae for most German PAYONE users.

I already have an email conversation with PAYONE technical support about this issue, but they told me that they cannot reproduce. Which is strange to me  since I can reproduce this in two installitons, one of them being a FRESH one.

Could you plese verify if this is expeted behaviour? Or is there anything I am missing here?

**Comment by T-Kuchel** [comment]
Hi skymeissner,

I have tried to repoduce that issue on a fresh installed 2.1.5 and 2.1.6 with sample data (to be sure i did that 2 times with both versions).
I always get your expected result (order is created, total paid is 0, total due is full amountand invoice is created, status is unpaid), wich is our expected result either.

Are you using the latest 'master' of the extension? I use (of course) the lastest one.

**Comment by skymeissner** [comment]
Did you cofigure the extension in any way. In my example I did not more than just add PAYONE access info. Anything that has to be configured for this to work?

**Comment by T-Kuchel** [comment]
No. I just entered the credentials and of course activate the payment method 'payone_invoice'.

**Comment by skymeissner** [comment]
It's my fault, I was indeed not using dev-master but was requiring 1.x.

But, tell me, why are you making another release? I usually don't require dev-master and I believe this is best practive on a project with semantic versioning. This issue is quite relevant and everybody who installs now with "composer require payone-gmbh/magento-2", like you  suggest in your docs, and like I did in my fresh install will have faulty invoice handling?

Sorry for the inconveniences and big thanks for your support!
