### ISSUE TITLE
payment.xml validation

### ISSUE THREAD

**Issue by c-walter** [PAYONE-GmbH/magento-2#574]
Hey, please check https://github.com/PAYONE-GmbH/magento-2/blob/e68394b16cbbb9f41721c59995eafdc3606579f7/etc/payment.xml#L48 for latest versions. There is a "v" in the xml which is there by mistake.

**Comment by Morgy93** [comment]
Fixed via https://github.com/PAYONE-GmbH/magento-2/pull/572

Please release ASAP 🙏

**Comment by JasiukiewiczM** [comment]
Fixed 3 weeks ago and still waiting for release? Why is that?

**Comment by Morgy93** [comment]
> We won't do a separate release for such a small change. This adjustment will be included in the next release.

Could you consider releasing a patch version? That’s exactly what they’re meant for.
A 3.13.2 release would be ideal.
Since 3.13.1 is currently broken, it would greatly benefit all users to have a fixed version available as soon as possible.

**Comment by janteuber** [comment]
Hi everyone,

I've fixed the issue from GitHub and released a new plugin version. Check it out here: [v3.13.2 Release](https://github.com/PAYONE-GmbH/magento-2/releases/tag/v3.13.2).

Thanks for your patience!

Best,
Jan
