### ISSUE TITLE
BNPL methods don't work using default settings

### ISSUE THREAD

**Issue by domeglic** [PAYONE-GmbH/magento-2#575]
I can't find much information on how BNPL methods are supposed to be configured to work correctly.

The documentation only states we need to use a separate portal and configure it. But according to Payone support we must also use preauthorization. When that is done orders are no longer automatically processed further, there is no invoice created because we are apparently supposed to manually capture it? We don't want to manually capture 100s of orders per day.

As I understand it the process should be:
- When appointed is recieved, order may be shipped
- When order is shipped, we should capture the payment to trigger the payment so user may recieve the emails on how to pay. 
- When it is paid, we would recieve the paid status

We must only capture the payment after shipping because doing so sends the email to the user that they must pay, but that should only happen when shipped, so we cannot just capture right away like with advance payment.

But does capture mean the same thing as in Magento? If I create an invoice in magento with capture online, it is already paid but it should not be. However, if I create it as not capture, will that trigger the process on the gateway?

This should all be either explained or part of the default functionality of the extension.

**Comment by janteuber** [comment]
The challenge with BNPL is that the capture triggers the due date. Therefore, the capture must be close to the shipping of the products. Whether there are a few minutes or even a few hours between shipping and capture is not important. The customer has enough time to pay. However, it is important, for example with furniture that needs to be manufactured first, that the capture does not occur too early. In Magento, we have linked the "capture" to the invoice creation.

**Comment by domeglic** [comment]
I understand that but it doesn't explain why there is no automatic capture when order is shipped.

Another problem as I explained is that creating an invoice in magento using capture online will mark the invoice as paid, while it is in fact not.   
I was hoping that we can trigger the BNPL capture but keep the invoice as open. Then when the invoice is actually paid we would get a transaction status paid and that would trigger this already existing observer (https://github.com/PAYONE-GmbH/magento-2/blob/master/Observer/Transactionstatus/Paid.php) to set the invoice as paid.

**Comment by janteuber** [comment]
We have fully followed the logic of M2 and send the capture with the invoice creation. We do this for all our payment methods in M2.

All three BNPL payment methods are secured payment methods. This means that once the order is in the shop, the products can be shipped without further verification. Once the order is captured, the money will be paid out to the merchant. The payout is guaranteed, regardless of if and when the customer actually pays. The status "paid" is completely irrelevant for the merchant in this context.

**Comment by domeglic** [comment]
What about the first part of my question regarding automation? All the other payments work fully automatic but this one doesn't. Merchant shouldn't be expected to click capture on each order, we get potentially over 100 orders a day.

**Comment by janteuber** [comment]
To automate processes, there are several options available. Some merchants integrate the capture request directly into their ERP systems. Alternatively, within Magento 2, the event to which the capture request is linked can be modified. Additionally, a surprising number of merchants use our PMI to send the capture request. 

As PAYONE, we will not implement a general automation feature in Magento 2, as it serves as a safety measure for merchants in cases where shipping and order placement are significantly time apart.

**Comment by domeglic** [comment]
Well this is going nowhere as I can't make it any clearer what the issue is than the last 3 times. So I will close it and maybe it will eventually get fixed like this one did #103.

From a merchants point of view, this doesn't work as expected. They use CC, sofort and advance payment. When they use those payments, nobody has to click anything. So now they want to use BNPL and it doesn't work. As my original comment says, this is not sufficently documented. It should clearly state that only preauthorization may be used and that it needs to be manually captured to proceed.
