### ISSUE TITLE
Sequence number incorrect with api requests

### ISSUE THREAD

**Issue by skymeissner** [PAYONE-GmbH/magento-2#60]
The sequnce number is stored only in table "payone_protocol_transactionstatus". When an API request occurs this number is fetched and incremented for that request only. The incremented sequence number is not saved. Making two consecutive api requests fails because the second tries to use the same sequence number.

Example:

1. Create order and have it paid.
2. Create a credit memo for a partial amount of total recevivable => works.
3. Create another credit memo for a partial amount => fails, wrong sequnce number.

**Comment by fjbender** [comment]
Did you leave wait time between steps 2 and 3 to make sure the transaction status has been processed? That can take up to 15-20 minutes in test mode.

**Comment by skymeissner** [comment]
Nope, I did not.  Sequence was number was incremented correctly with the callback!
