### ISSUE TITLE
New invoice order handling

### ISSUE THREAD

**Issue by skymeissner** [PAYONE-GmbH/magento-2#63]
With the "new" invoice handling an invoice is created and paid when payment occurs. However, if the merchant creates an invoice _before_ the order is paid (my customer wants to create and send the invoice immediately after order generation, including payment method invoice ) the status updates creates a second invoice with a grand total of 0 and pays that.

It would be better if the status update would detect an existing invoice for that order and pay that.

I'll attach a pull request in a minute.

**Comment by skymeissner** [comment]
PR #64

**Comment by fjbender** [comment]
Fixed with #140
