### ISSUE TITLE
Order confirmation sent when payment failed

### ISSUE THREAD

**Issue by davidverholen** [PAYONE-GmbH/magento-2#70]
yesterday, we had the case, that a payment could not be completed because the mastercard was not registered for mastercard securecode (regarding to the error message of the cc provider).

after the payment failed, order confirmations have still been sent to the customer.

**Comment by fjbender** [comment]
We're currently looking for a clean way to fix this.

**Comment by fjbender** [comment]
With #66 we introduced that order e-mails are only sent when the order is confirmed by Payone.

I'd rather not refactor the entire order creation process. Experience shows that when the order is only created upon the customer returning to the shop, we end up with payments with no corresponding orders, which to me seems like the bigger mess than orders without payments.

I'd suggest you take a look at the changes introduced in #66 and see if they fit your use case.

**Comment by davidverholen** [comment]
basically it's looking good to me. will there be a new stable release soon?

**Comment by fjbender** [comment]
I guess I can make one after lunch.

**Comment by davidverholen** [comment]
now it seems that mails for the paymernt method cash on delivery (for example) are not sent at all

**Comment by SMunker** [comment]
It seems this changes has been created a new bug. Now I have the same problem as davidverholen.
Now, no order confirmation email will be sent for my active payment methods like credit card, cash on delivery, advance payment and SOFORT Überweisung.

**Comment by fjbender** [comment]
Sorry, i completely overlooked your comment. 

@davidverholen do you have more info on this issue by chance?

**Comment by SMunker** [comment]
I changed in file /Model/Methods/PayoneMethod.php at line 111 from
`$oOrder->setCanSendNewEmailFlag(false);`
to
`$oOrder->setCanSendNewEmailFlag(true);`

This change works for me. But I don't know if it solves the original problem.

**Comment by davidverholen** [comment]
For us it's working now. But cash on delivery mail for example is delayed until payment confirmation through payone. You habe to make sure that payone can send transaction updates though

**Comment by hreinberger** [comment]
this looks done to me. Feel free to open a fresh issue if you're still having problems.
