### ISSUE TITLE
Credit memo adjustment causes error

### ISSUE THREAD

**Issue by berwa** [PAYONE-GmbH/magento-2#71]
Setup: Magento CE 2.1.4, module-version 1.3.2

Steps to reproduce:
- Place order e.g. with payment-method Paypal
- Create an invoice for the placed order (capture online)
- Try to create an credit memo with only an adjustment: 
  - change to invoice-details 
  - click 'Credit memo'
  - set item-qty(s) to 0
  - click 'Update Qty's'
  - enter a value (e.g. 10) in text field next to 'Adjustment Refund'
  - click 'Refund'

Result: An error message is displayed '950 - An error occured while processing this transaction (wrong parameters).', no refund is created.

Expected result: A refund is created matching the amount of money entered (10 € in the example above).

Additional information: the above mentioned steps do work for Magento default refunding (by clicking 'Refund Offline' instead of 'Refund').

**Comment by fjbender** [comment]
@berwa I just tried to reproduce this behavior, but it works fine in my system.

Error code 950 indicates that prior transaction status notifications have not yet been processed by the shop. Please make sure your transaction status URL is configured correctly in the PMI and the notifications reach your shop. You can call our Technical Support Team at +49 431 25968-500 if you need any assistance.
