### ISSUE TITLE
Is the extension ready for enterprise database clustering

### ISSUE THREAD

**Issue by wetzesa** [PAYONE-GmbH/magento-2#75]
Hi...

we would like to use the extension in a Mage 2 EE project with database clustering like described here.
http://devdocs.magento.com/guides/v2.0/config-guide/multi-master/multi-master.html

Is the extension ready for working in both modes ("single" db and clustered db)?

Regards

**Comment by fjbender** [comment]
Hi @wetzesa 

We discussed this in #22 but dismissed the issue due to insufficient information. If you have any more insights into this topic, please reopen the original issue.

Thanks
Florian
