### ISSUE TITLE
Please create releases with minor number change for bugfixes

### ISSUE THREAD

**Issue by sydekumf** [PAYONE-GmbH/magento-2#80]
The latest release is from 18th of May, since then many bugfixes have been comitted but no release has been created. Can you please create a release with the increase of the minor number for that?

Otherwise I have to clone the repository which I don't want :-) Would be great :-)

**Comment by fjbender** [comment]
Just waiting on #81 and then I'll get right to it.

Cheers
Florian

**Comment by fjbender** [comment]
It's done.
