### ISSUE TITLE
Address validation error leads to PHP Notice

### ISSUE THREAD

**Issue by sydekumf** [PAYONE-GmbH/magento-2#83]
Hi there,

we had an address validation error (which is correct as the address was not correct) but the response from Payone lead to a PHP notice in the module.

In https://github.com/PAYONE-GmbH/magento-2/blob/master/Model/Api/Request/Consumerscore.php#L118 it is expected that the response has the `score` field, but in a case of a wrong address the response looks like:

```
[04-Jul-2017 07:29:34 UTC] array (
  'status' => 'INVALID',
  'errorcode' => '4041',
  'secstatus' => '30',
  'errormessage' => 'Address not found',
  'customermessage' => 'Address not found. Please verify your data.',
)
```

That is the reasons why line 118 throws a notice and nothing happens in the frontend (no message).

Thanks for your help :-)

**Comment by fjbender** [comment]
We'll look into it (MAG2-33).

**Comment by sydekumf** [comment]
What is the current status of this? We are still experiencing the issue :-)

**Comment by T-Kuchel** [comment]
We ( @FATCHIP-GmbH  ) are still working on that. We'll inform you  immediately when this issue is solved.
Thank you for your patience!
