### ISSUE TITLE
Bei der Bearbeitung dieser Transaktion ist ein Fehler aufgetreten (Falsche Parameter).

### ISSUE THREAD

**Issue by jignesh26** [PAYONE-GmbH/magento-2#85]
Hello, 

 We have updated magneto version 2.1.7 and have latest module from payone. 1.3.4. but when we try to place order using the test mode. its saying that.  "Bei der Bearbeitung dieser Transaktion ist ein Fehler aufgetreten (Falsche Parameter)."

Please help us in that
Thank you.

**Comment by fjbender** [comment]
Hi @jignesh26 

Most likely our API refuses the request you made because of a configuration error.  Please contact our Technical Support team at tech.support@payone.com stating your merchant ID and if possible date and time of the error so they can take a look at the logs.

cheers
Florian
