### ISSUE TITLE
Missing default value for payone_general/global/request_type

### ISSUE THREAD

**Issue by a-t-s** [PAYONE-GmbH/magento-2#86]
Hi!
Low priority issue.
There is no default value given for xpath payone_general/global/request_type in etc/config.xml (no such node).
If you configure payone only for one website for instance (no global values in core_config_data) and take what you see for granted (the config source model shows a "preauthorization" default - see attached image) ... no request_type is sent and thus you end up with the API errormessage | Parameter {request} faulty or missing.
<img width="842" alt="bildschirmfoto 2017-07-19 um 15 35 12" src="https://user-images.githubusercontent.com/10349826/28369453-ec377d6c-6c97-11e7-805b-97ca7f42ac66.png">

I suggest you either provide a default value in the config.xml or make the `        <source_model>Payone\Core\Model\Source\RequestType</source_model>
` return an additional empty value to show the request_type config field is "required".

**Comment by fjbender** [comment]
We'll take a look. Thanks for your input!
