### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed

### ISSUE THREAD

**Issue by marcmmx** [PAYONE-GmbH/magento-2#89]
After installation of the extension I get following error message on the frontend. The Backend is working.

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Customer\Model\AccountManagement::__construct() must be an instance of Magento\Customer\Model\CustomerFactory, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/viktoriamed/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /var/www/viktoriamed/vendor/magento/module-customer/Model/AccountManagement.php:316 Stack trace: #0 /var/www/viktoriamed/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Customer\Model\AccountManagement->__construct(Object(Magento\Framework\ObjectManager\ObjectManager)) #1 /var/www/viktoriamed/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('LitExtension\\Cu...', Array) #2 /var/www/viktoriamed/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('LitExtension\\Cu...') #3 /var/www/vi in /var/www/viktoriamed/vendor/magento/module-customer/Model/AccountManagement.php on line 316

**Comment by fjbender** [comment]
Can you supply more details about how exactly you installed the module, i.e. which commands you ran and whether they all completed successfully?

Cheers
Florian

**Comment by marcmmx** [comment]
Of course.
I followed exactly the steps from here
https://github.com/PAYONE-GmbH/magento-2

```
composer require payone-gmbh/magento-2
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean
```

finally I made in the installation directory of magento 2:
`chown -R www-data:www-data .`
and
`chmod 700 /var/www/viktoriamed/app/etc`

**Comment by fjbender** [comment]
Sounds good so far. However, I'm not sure if it's our extension causing the problem. The stacktrace hints towards another extension `create('LitExtension\Cu...')`. Try disabling the "LitExtension" and see whether this changes anything.

**Comment by marcmmx** [comment]
Re-installation and another deploy has fixed the problem.
