### ISSUE TITLE
PayPal fails on pre-authorization | working on direct-authorization

### ISSUE THREAD

**Issue by lfritsche** [PAYONE-GmbH/magento-2#94]
Hi there ;)

Magento 2.1.5
PayOne Extension in most recent version.
Payment Method: PayPal

If I switch the authorization method to "pre-authorization" the redirect back to the shop fails.
After successfully logging in at paypal and confirming the payment I should see a redirect to the checkout success page, but instead I see the checkout page (step 1) again without any error message. The Payone Response status is: "REDIRECT" and I don't see any error message or error code and the order status is cancelled.
Payone status: ` 902 (Unbekannter Fehler bei externem Dienstleister.) `

Everything is fine, if I select "authorization" as authorization mode.

Do you have any idea, or need further information about my configuration settings?

Thank you in advance!

**Comment by fjbender** [comment]
Hi and fhanks for your feedback!

To me, this sounds like an issue with configuration of your merchant account on the plattform. Please contact the Technical Support Team and have them look at this specific transaction (have your merchant ID and date/time of the request ready).

If they can't find anything, please come back here and we'll see if there's an issue with the plugin.

Cheers
Florian
