### ISSUE TITLE
Can't place order with Creditcard when JS is merged/minifed/bundled

### ISSUE THREAD

**Issue by domeglic** [PAYONE-GmbH/magento-2#97]
**Preconditions**
- Store is in production mode 
- Javascript is merged/minified/bundled: _Stores->Configuration->(Advanced)Developer->Javascript settings_
- Magento v2.1.6 (with sample data)
- module v1.3.5

In the checkout, choosing creditcard and placing an order will not work. The fullscreen loader is started, one ajax request is made (to secure.pay1.de) but nothing else happens. There are no javascript errors.
The same works if the javascript is not merged/minified.

I had a quick look and my best guess is that it doesn't work because function **processPayoneResponseCCHosted(response)** is not accessible when merging/bundling is enabled.
This is the function that leads to the redirect being made and if I try to call this function in browsers console it does not exist in merged/bundled mode.

This function is defined [here](https://github.com/PAYONE-GmbH/magento-2/blob/974d9ea05162d1bed972e62e292a338665b30ae8/view/frontend/web/js/view/payment/method-renderer/creditcard-method.js#L165)

**Comment by sydekumf** [comment]
Hi there, glad to see this ticket! We also had this issue on 2 (two!) completely separate instances (different customers). We talked to the Payone Technical Support and they tried to reproduce the issue. Unfortunately they told us they can not reproduce it.

The problem is still there and we were forced to deactivate merging/bundling/minifying which of course leads to a poor shop performance in the frontend.

We are really looking forward to a fix :-) Thanks!

**Comment by fjbender** [comment]
Good news is, I can reproduce the problem. Development will have a look at this soon.

**Comment by domeglic** [comment]
I added a workaround for this in my project, although it is not really well tested and not in production yet.
The workaround is a mixin that sets [this](https://github.com/PAYONE-GmbH/magento-2/blob/974d9ea05162d1bed972e62e292a338665b30ae8/view/frontend/web/js/view/payment/method-renderer/creditcard-method.js#L165) function to the window property directly.

```define(
    [
        'jquery',
        'Payone_Core/js/view/payment/method-renderer/base',
        'Magento_Ui/js/model/messageList',
        'mage/translate',
        'Magento_Checkout/js/model/full-screen-loader'
    ],
    function ($, Component, messageList, $t, fullScreenLoader) {
        'use strict';
        var mixin = {
            handleCreditcardCheck: function () {
                this._super();
                window.processPayoneResponseCCHosted = window.processPayoneResponseCCHosted || function (response) {
                        window.ccjs.processPayoneResponseCCHosted(response);
                    };
            }
        };
        return function (target) {
            return target.extend(mixin);
        };
    }
);
```

**Comment by fjbender** [comment]
@domeglic Thanks, this should probably point us in the right direction.

**Comment by fjbender** [comment]
PR #99 fixes this issue for me. Can anyone confirm?

Cheers
Florian

**Comment by sydekumf** [comment]
Hi, unfortunately credit card still does not work with activated JS merging/bundling/minifying. Safe Invoice does work.
